### ISSUE TITLE
master-thesis 竖排题目优化

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#112]

**Comment by secure918** [comment]
请问竖排题目中的英文部分应该怎么处理呢？

**Comment by fky2015** [comment]
> 请问竖排题目中的英文部分应该怎么处理呢？

请您新建一个 Issue，并提供更详细的说明。

比如你所指的是英文的缩写，还是全拼单词。以及您的输入在 Word 中本来的行为是什么。

比如竖排这个问题，其实决定一个英文单词应该是竖着排列还是横着排列，应该看研究生院的要求，抑或是 Word 文档里竖排的行为。

补充一点，“竖排“其实一直没有统一的排版方式，很多时候大家都是按照“约束 + 自己的习惯”处理的。
