### ISSUE TITLE
更新版本后的参考文献问题

### ISSUE THREAD

**Issue by FrankLiang3196** [BITNP/BIThesis#141]
在更新了latex版本之后发现参考文献无法显示了，请问有什么解决办法吗？现在历史版本提供的下载链接也都速度慢到下载不下来。太难受了

**Comment by fky2015** [comment]
请提供以下你使用的是哪个模板（本科亦或是硕士），你的编译方法是什么？
是否按照我们的 [wiki](https://bithesis.bitnp.net/Guide/2-Usage/Downloading-and-using-templates.html#%E4%BD%BF%E7%94%A8-vs-code-%E6%92%B0%E5%86%99%E4%B8%8E%E7%BC%96%E8%AF%91-latex-%E6%A8%A1%E6%9D%BF) 正确地配置了自己的编辑器？

如果使用 Github 不方便的话可以加入我们的 QQ 群。

**Comment by FrankLiang3196** [comment]
您好！我使用的是本科毕设模板，现在是mactex的2021版，我用的是Texpad编译的。请问QQ群怎么加啊？谢谢啦！

>

**Comment by fky2015** [comment]
737548118
