### ISSUE TITLE
文献翻译的封面的外文原文题目和中文翻译题目排版和word封面不完全一致

### ISSUE THREAD

**Issue by everything411** [BITNP/BIThesis#144]
### 发生了什么？

latex版
![1654509938031](https://user-images.githubusercontent.com/32010059/172140578-f76ca3b1-6d52-40b3-81b7-50f89ebcf382.png)
word版
![1654509985962](https://user-images.githubusercontent.com/32010059/172140690-091fdcae-e030-4f4c-9d5b-1733e00c570a.png)
其中word版按照提示进行换行时的行为
![1654510062220](https://user-images.githubusercontent.com/32010059/172140878-8a825554-3c69-4c64-befb-b40638db03f6.png)
此问题是否有较好的在模板层次解决的方案，还是说只能手工调整？

### 问题复现的步骤

无

**Comment by fky2015** [comment]
> 此问题是否有较好的在模板层次解决的方案，还是说只能手工调整？

现在的 LaTeX 封面是根据老的文献翻译封面（特意）制作的，确实需要更新模板。
