### ISSUE TITLE
[Bug]: 3.0.1 与3.0.2 的博士论文选项在overleaf和自建ol上均无法编译

### ISSUE THREAD

**Issue by KaysinBIT** [BITNP/BIThesis#175]
### 发生了什么？

错误如 LaTeX3 Error: Key 'bithesis/option/type' accepts only a fixed set of

### 问题复现的步骤

type=doctor

### 操作系统或平台

Overleaf

### LaTeX 发行版以及发行年份

2022

### BIThesis 模板

graduate-thesis

### 日志信息

```shell
(LaTeX3)        choices.

For immediate help type H <return>.
 ...                                              
                                                  
l.324 \ProcessKeysOptions { bithesis / option }
```

**Comment by fky2015** [comment]
非常感谢您的及时反馈，修复的版本已经在 V3.0.3 释出。

如果您使用 Overleaf，可以考虑重新复制模板。

https://github.com/BITNP/BIThesis/releases/tag/v3.0.3

**Comment by KaysinBIT** [comment]
> 非常感谢您的及时反馈，修复的版本已经在 V3.0.3 释出。
> 
> 如果您使用 Overleaf，可以考虑重新复制模板。
> 
> https://github.com/BITNP/BIThesis/releases/tag/v3.0.3

感谢修复！

**Comment by fky2015** [comment]
Close as per the fix in v3.0.3.
