### ISSUE TITLE
Add a cross-platform makefile

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#180]

**Comment by YDX-2147483647** [comment]
If non-ubiquitous tools like `rg`, `entr`, `jq` are accepted, I suggest [`just`](https://just.systems/man/en/).

Features:

- [Recipe Attributes](https://just.systems/man/en/chapter_31.html#recipe-attributes) to make recipes behave differently depending on OS.

  ```just
  [unix]
  run:
    cc main.c
    ./a.out
  
  [windows]
  run:
    cl main.c
    main.exe
  ```

- [Functions](https://just.systems/man/en/chapter_30.html#system-information) about system information.

  ```just
  python_dir := if os_family() == "windows" { "./.venv/Scripts" } else { "./.venv/bin" }
  ```

**Comment by fky2015** [comment]
I've considered Just too, and that's fine with me. I have no preference on which toolchain this project should use.

**Comment by fky2015** [comment]
I've invited you to have write access to this repo. If you believe this issue is no longer low-priority, please remove the `Await` label.

**Comment by fky2015** [comment]
Also: #227
