### ISSUE TITLE
[Bug]: 超链接跳转位置错误

### ISSUE THREAD

**Issue by oPengLuo** [BITNP/BIThesis#200]
### 发生了什么？

自动生成的目录中，点附录A却跳转到正文第一章

### 你期望的结果

点目录中的附录A，正常应该跳转到附录A那里

### 问题复现的步骤

研究生论文模板就有这个问题

### 操作系统或平台

Linux

### LaTeX 发行版以及发行年份

Texlive 2022

**Comment by scliubit** [comment]
应该是模板里面定义appendices的时候\setcounter{chapter}{0}导致的，让这一段直接连接到第一个chapter去了

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/releases/tag/v3.2.3-alpha-1 修复了此问题， @oPengLuo 能否帮忙测试一下？

**Comment by oPengLuo** [comment]
> 

完美解决问题！
