### ISSUE TITLE
bibtex编译后的专利格式与学校官方专利格式有差别

### ISSUE THREAD

**Issue by haohaolalahao** [BITNP/BIThesis#209]
### 发生了什么？

bibtex编译后的专利格式与学校官方专利格式有差别
- bibtex编译的专利格式：
<img width="510" alt="image" src="https://user-images.githubusercontent.com/30471665/212696075-c8b98499-c73d-4062-a43a-ac3a0f47c4aa.png">
- 学校官方专利格式：
<img width="511" alt="image" src="https://user-images.githubusercontent.com/30471665/212696176-3b2c5ca5-dad1-4f6f-9e66-7b23b1a5e4f1.png">
问题：专利号、专利标志与国别字段顺序错误

### 问题复现的步骤

- 使用latexmk编译
- 专利bib字段：
@patent{zhuanlidemo,
  title={一种基于知识蒸馏的多模光电小目标识别方法},
  author={Li, Wei and Wang, Hao and Huang, Zhanchao and Tao, Ran},
  location={中国},
  number={ZL202110798886.9},
  year={2022-08-30},
}
- windows/macOS均测试过
- 模板是研究生论文模板
- 可能需要修改字段顺序，但个人不太会

### 操作系统或平台

macOS

### LaTeX 发行版以及发行年份

macTex

### BIThesis 模板

undergraduate-thesis

**Comment by fky2015** [comment]
### 为什么会出现这个问题？

推测原因，学校采用了一种不符合国标（无论是 1987、2005 还是 2015 版本）的格式。而我们采用的是 GB/T 7714-2015 的标准（底层为 https://github.com/hushidong/biblatex-gb7714-2015）。因此在此处格式产生了冲突。

### 解决方案一（快速）

首先定义一下指代对象：
1. 学校在《规范》中提供的格式称为「学校的格式」
2. 目前我们采用的格式称为「我们的格式」

目前，如果没有老师强行要求的话，我建议可以先忽略这个问题。
原因如下：
1. 在学校提供的已经不维护的 LaTeX 模板中，编译出来的专利格式也是不符合「学校的格式」的要求的。
2. 本科生和研究生的「学校的格式」在此处都有相同的问题，而学校在本科生的模板规范处特别说明了“可参考 GB 7714-2015”（我们的格式）。 当时跟学校教务部（负责本科生）的老师确认过，我们可以使用 GB 7714-2015 来处理不一致行为。

### 解决方案二（只是目前的设想）

我会尝试提供一个符合「学校的格式」的著录格式，但是这项工作比较费时，无法在短时间内完成。
并且，覆盖国标的格式可能需要用户手动添加代码，我需要一段时间去调研这个问题。

**Comment by fky2015** [comment]
### 为什么会产生这个问题
首先确定一下指代对象：

- 学校提供的格式称为「学校的格式」
- 我们采用的格式称为「模板的格式」（https://github.com/hushidong/biblatex-gb7714-2015）
学校采用了一种与国标（1987、2005 以及 2015）有出入的格式，而我们采用的是 GB 7714-2015。因此在这里出现了冲突。

### 解决方案一（快速）
如果没有老师明确要求，可以忽略它。
原因如下：

1. 学校提供的已经不维护的 LaTeX 模板中，采用的格式也与「学校的格式」不一致。
2. 学校的本科生和研究生的标准在这里均有这个不太规范的规定；而本科生那边已经明确回复过，遇到冲突可以采用「模板的格式」——也即国标。
### 解决方案二（慢速）
我会尝试修改「模板的格式」以符合「学校的格式」，但是这需要较大量的工作，所以短时间无法完成。

**Comment by haohaolalahao** [comment]
非常感谢！！！🥳

**Comment by fky2015** [comment]
我们发布了一个测试版，你可以尝试帮我们测试一下吗：
https://github.com/BITNP/BIThesis/releases/tag/v3.3.0-alpha-1

**Comment by haohaolalahao** [comment]
可以的，我今天测试完给反馈！

**Comment by haohaolalahao** [comment]
非常感谢！「学校的格式」测试没有问题，完全符合要求
<img width="467" alt="image" src="https://user-images.githubusercontent.com/30471665/216051626-8c7e52fa-3dcd-4246-bff3-3d1728881487.png">
