### ISSUE TITLE
[Bug]: 博士论文双页模式添加空白页问题

### ISSUE THREAD

**Issue by KaysinBIT** [BITNP/BIThesis#220]
### 发生了什么？

新章节前不需要添加空白页

### 问题复现的步骤

双页模式

### 操作系统或平台

Overleaf

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
目前「新章节在右手页另起」的格式是延续原有的模板样式的。请问这个地方有什么特殊需求吗？

**Comment by KaysinBIT** [comment]
> 目前「新章节在右手页另起」的格式是延续原有的模板样式的。请问这个地方有什么特殊需求吗？

目前已无此要求，正文内连续即可。

**Comment by fky2015** [comment]
那我先针对这个样式增加一个配置选项，然后后期我会咨询一下教务部的老师，再确认一下这个问题。

**Comment by fky2015** [comment]
> 目前已无此要求，正文内连续即可。

还是要和你确认一下具体哪些内容不需要在右手页另起。

正文是否包括“参考文献”或者“附录”？
