### ISSUE TITLE
[Bug]: 当设置 `schoolEn` 或 `majorEn` 为较长英文时，封面格式会出现错位

### ISSUE THREAD

**Issue by spencerwooo** [BITNP/BIThesis#231]
### 发生了什么？

在 `\BITSetup` 中，当设置比如 `schoolEn`、`majorEn` 为较长英文时，封面格式会出现错位和排版错误。

### 你期望的结果

正常的封面排版。（详见第 4 节。）

### 问题复现的步骤

设置二者为网络空间安全学院的英文全称：

- `schoolEn`: School of Cyberspace Science and Technology
- `majorEn`: School of Cyberspace Science and Technology

### 最小可复现用例或者截图

|正常封面|凌乱的封面|
|:-:|:-:|
|![CleanShot 2023-02-17 at 23 03 19@2x](https://user-images.githubusercontent.com/32114380/219690207-46a909b3-ce59-414f-8bcd-5097df79e63c.png)|![CleanShot 2023-02-17 at 23 03 54@2x](https://user-images.githubusercontent.com/32114380/219690329-d599c4cb-cf9c-4947-a6a6-19ba7c6fafc3.png)|

### 操作系统或平台

macOS

### LaTeX 发行版以及发行年份

MacTeX 2022

### BIThesis 模板

graduate-thesis

**Comment by spencerwooo** [comment]
如果不加上 School of 地方是够的，但是如果带着的话就会出现右图的情况。

**Comment by fky2015** [comment]
如需要换行，则用 “\\” 符号分割。

```
majorEn = School of \\ Cyberspace Science and Technology
```

![image](https://user-images.githubusercontent.com/16451516/219695376-e59a70d0-3eb6-4aa3-8249-497a7e0b371c.png)

**Comment by spencerwooo** [comment]
了解，这一行为和在 Word 模板里是一致的吗？（指的是长度过长需要换行的话，则另起单独带下划线的一行。）

**Comment by fky2015** [comment]
学校没有明确要求。但现在这种方式比较尊重传统的使用习惯。这个行为模拟的是“采用表格约束封面项”的方式，用户手动换行以后，等价于在表格中添加了一行。

学校提供的 Word 模板实际上在这里的处理比较糟糕的——因为简单使用了空格来分割标签和值，导致超出内容自动/手动换行会破坏样式：

![image](https://user-images.githubusercontent.com/16451516/219829058-934b2460-aa3e-49db-8472-a7041f0199bd.png)
![image](https://user-images.githubusercontent.com/16451516/219828759-def2dada-777d-4053-a3c9-2ac7106f53c0.png)

不过确实，你提到的鬼畜封面行为确实比较吓人，应该约束一下。这是因为计算的表格宽度的时候，是按照最长行计算的。那么一行文字比较长了以后就会影响整体样式。感觉可以考虑设置一个最大宽度约束一下。（但是用户还是需要手动换行的）

**Comment by fky2015** [comment]
所以说按照目前的这个情况，我们还有必要针对这个问题做优化吗？

**Comment by spencerwooo** [comment]
我觉得要不就忽略掉吧，留着这个 issue 当作一个针对此问题的提示就行了。
