### ISSUE TITLE
攻读学位期间发表论文与研究成果清单-四作以上的情况

### ISSUE THREAD

**Issue by BIT-MJY** [BITNP/BIThesis#233]
### 发生了什么？

攻读学位期间发表论文与研究成果清单中，若出现自己是四作以上的情况，则并不能将本人作者名字显示并加粗。即：
```
@INPROCEEDINGS{test_paper,
  author={Zhang, San and Li, Si and Wang, Wu and Ma, Liu},
  author+an = {4:myself="\Author"},
  booktitle={xxxxx}, 
  title={xxxxx}, 
  year={xxxxx},
  pages={xxxxx},
  annotation = {xxxxx},  
  }
```
上述案例下，本人Ma, Liu无法显示。

### 你期望的结果

本人Ma, Liu的名字也能显露并加粗

**Comment by fky2015** [comment]
感谢你的反馈！

等下一版本的模板发布以后，将可以在 `\BITSetup` 中指定最长作者数量：

```
\BITSetup {
...,
  publications = {
    maxbibnames = 4,
  }
}
```

**Comment by BIT-MJY** [comment]
感谢如此快速的回复！

根据您的新公布版本，问题已经解决，但是发现了一个可以进一步优化的地方：比如一篇论文一共有6个作者，我是第4个作者，这时候设置maxbibnames = 4或5，对于这一条引用仍然是无效的，必需要设置maxbibnames = 6才能显示出我的名字。如果可以的话，希望作者以后能解决这个问题。十分感谢您对北理latex论文模板的贡献！

**Comment by fky2015** [comment]
不好意思，是之前的实现有问题。现在可以通过同时设置 `maxbibnames` 和 `minbibnames` 来解决这个问题了：

![image](https://user-images.githubusercontent.com/16451516/219857525-be9a90fa-420e-4ccf-a7cb-30b3586b7617.png)

**Comment by BIT-MJY** [comment]
Done!

感谢您的再次指导。我在按照今天release的最新版本添加了对应的min设置，然后根据您的指导设置了minbibnames，上述问题已经解决 :-D
```
  minbibnames .int_set:N = \l__bithesis_publications_minbibnames_int,
  minbibnames .initial:n = {1},

 \cs_set:Npn \blx@minbibnames {
        \l__bithesis_publications_minbibnames_int
      }
....
