### ISSUE TITLE
Consider sunsetting template `undergraduate-proposal-report`

### ISSUE THREAD

**Issue by spencerwooo** [BITNP/BIThesis#245]
据我了解，目前计算机学院本科毕业设计的开题已经改版，不需要提交文档材料，只需要系统中自行填入相关内容即可。如果确实是这样，可以考虑停止维护 `undergraduate-proposal-report` 模板。（我再去确认一下，如果有变更在此 issue 更新。）

**Comment by fky2015** [comment]
我这边也确认这个事实了。

- [ ] 删除 `templates` 中相关代码、相关 CI。
- [ ] 在 wiki、手册中删除相关说明或标明变化。
- [ ] `bithesis.dtx` 中不对源代码进行删除。
