### ISSUE TITLE
本科毕业论文以及外文翻译的封面缺少班级信息

### ISSUE THREAD

**Issue by miniAtom** [BITNP/BIThesis#246]
### 发生了什么？

本科毕业论文以及外文翻译的封面缺少班级信息，并且外文翻译布局不够美观，上下间距不合适。

![Snipaste_2023-03-03_22-38-54](https://user-images.githubusercontent.com/75769380/222756322-e9d072c2-3101-4b09-a582-3493326575c1.png)

### 你期望的结果

希望可以在封面添加班级信息，并且调整外文翻译布局，谢谢！

### 问题复现的步骤

无

### 操作系统或平台

None

### BIThesis 模板

paper-translation, undergraduate-thesis

**Comment by fky2015** [comment]
See #247

**Comment by miniAtom** [comment]
【自动回复】来信已收到，十分感谢！
