### ISSUE TITLE
研究生学位论文模板参考文献格式有误

### ISSUE THREAD

**Issue by Artificialimbecile** [BITNP/BIThesis#258]
### 发生了什么？

使用overleaf，当文献类型为会议论文时，生成的参考文献会出现错误的双斜杠//。例如下面的文献：

@inproceedings{felzenszwalb2008discriminatively,
  title={A discriminatively trained, multiscale, deformable part model},
  author={Felzenszwalb, Pedro and McAllester, David and Ramanan, Deva},
  booktitle={2008 IEEE conference on computer vision and pattern recognition},
  pages={1--8},
  year={2008},
  organization={Ieee}
}

生成的文献为：
Felzenszwalb P, McAllester D, Ramanan D. A discriminatively trained, multiscale, deformable part model[C]//2008 IEEE conference on computer vision and pattern recognition. 2008: 1-8.

### 你期望的结果

Felzenszwalb P, McAllester D, Ramanan D. A discriminatively trained, multiscale, deformable part model[C]. 2008 IEEE conference on computer vision and pattern recognition. 2008: 1-8.

### 问题复现的步骤

1. overleaf中添加会议论文的引用；
2. 编译后即可复现。

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2022

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
`v3.4.3` 已经修复此问题。
