### ISSUE TITLE
硕士学位论文模板中，研究成果清单中没有显示完整作者列表，而只有et al.

### ISSUE THREAD

**Issue by JerrryNie** [BITNP/BIThesis#270]
### 发生了什么？

在overleaf中使用[BIThesis-graduate-thesis-v3.4.3](https://www.overleaf.com/project/64130038cf16e2c14c560c66)时，当给reference/pub.bib中添加研究成果的bib item后，**攻读学位期间发表论文与研究成果清单**里论文作者的完整列表没有显示出来

### 你期望的结果

显示完整的作者列表而非"et al."

### 问题复现的步骤

1. 在reference/pub.bib中添加NIPS2017_3f5ee243的bib信息
2. 在misc/pub.tex中的``\addpubs{}``中添加``NIPS2017_3f5ee243``

### 最小可复现用例或者截图

在reference/pub.bib中添加：
```bibtex
@inproceedings{NIPS2017_3f5ee243,
 author = {Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, \L ukasz and Polosukhin, Illia},
 booktitle = {Advances in Neural Information Processing Systems},
 editor = {I. Guyon and U. Von Luxburg and S. Bengio and H. Wallach and R. Fergus and S. Vishwanathan and R. Garnett},
 pages = {},
 publisher = {Curran Associates, Inc.},
 title = {Attention is All you Need},
 url = {https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf},
 volume = {30},
 year = {2017}
}
```
并在misc/pub.tex中的``\addpubs{}``中添加``NIPS2017_3f5ee243``

效果如下图所示：
![image](https://user-images.githubusercontent.com/26685684/228456344-35b67612-f5a5-4fbc-a1df-385d14fee755.png)

然而期望的结果不是et al.而是完整的作者列表

### 操作系统或平台

Overleaf

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
可以参考手册中 `5.7.3` 部分的 `maxbibnames` 和 `minbibnames` 进行配置。

**Comment by JerrryNie** [comment]
> 可以参考手册中 `5.3.7` 部分的 `maxbibnames` 和 `minbibnames` 进行配置。

非常感谢，问题已经解决！

**Comment by JerrryNie** [comment]
> 另外，想知道对于你来说，你觉得这部分提示内容应当放在哪里更容易让用户找到呢？

因为我一般习惯上会去看latex里面的注释，根据注释中的说明来编辑文档，所以我个人是觉得可以把maxbibnames和minbibnames变量**显式**加在`main.tex`中，并配上一两句注释，可能会让用户容易看到。
