### ISSUE TITLE
[Bug]: 表格目录页面的底部页码错误

### ISSUE THREAD

**Issue by c-my** [BITNP/BIThesis#276]
### 发生了什么？

在初始模板中，将“主要符号对照表”页面注释掉后，“表格目录”页面的页码是“1”，而不跟随前一页目录的罗马数字。

但在保留“主要符号对照表”页的情况下，“表格目录”页面的页码是正常的罗马数字。

### 你期望的结果

“表格目录”页面的底部页码不是1。

### 问题复现的步骤

1. 打开默认模板
2. 注释掉 ` \input{./misc/0_symbols.tex}`
3. 编译

### 最小可复现用例或者截图

~~~latex
\frontmatter

% 摘要
\input{./chapters/abstract.tex}

% 制作目录
\MakeTOC

% 插图目录
\listoffigures
% 表格目录
\listoftables

% 主要符号对照表
% 注释掉这一页
% \input{./misc/0_symbols.tex}

\mainmatter

% 请根据论文内容，按照顺序添加章节。
\input{./chapters/chapter1.tex}
\input{./chapters/chapter2.tex}
~~~

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2023

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
已确认该问题，将在 `v3.5.1` 版本修复。非常感谢您的帮助！
