### ISSUE TITLE
[Bug]: 把引用文献放到图片标题中会导致引用标号错误

### ISSUE THREAD

**Issue by baixiao643343** [BITNP/BIThesis#283]
### 发生了什么？

硕士毕设模板中，当我把引用文献（也就是\cite{xxx}）放到图片标题中（caption{abc}），也就是这样的：caption{abc\cite{xxx}}，会导致引用标号显示错误，即全文的文献引用右上标都变为[0]，引用文献也的序号也都是[0]。引用的文献都是bib文件里放好的。

### 问题复现的步骤

在图片标题（caption{abc}）中加入引用文献（也就是\cite{xxx}）

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2023

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
@baixiao643343 请问你的问题解决了么？

**Comment by fky2015** [comment]
因为不活跃且无法复现问题而关闭此 Issue。

如果有相关问题，可以随时重新开启。
