### ISSUE TITLE
[Bug]: 4级标题的行距貌似太大了

### ISSUE THREAD

**Issue by c-my** [BITNP/BIThesis#285]
### 发生了什么？

4级标题的行距看起来很大

### 你期望的结果

4级标题的行距看起来正常

### 问题复现的步骤

1. 输入4级标题 `\subsubsection{xxxx}`
2. 编译

### 最小可复现用例或者截图

![图片](https://user-images.githubusercontent.com/22538534/231406698-f8c93699-e4f8-4075-9d87-52b8d953d3f9.png)

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2023

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
确实
