### ISSUE TITLE
[Bug]: 列表项的行距过大

### ISSUE THREAD

**Issue by c-my** [BITNP/BIThesis#293]
### 发生了什么？

列表项之间的行距看起来有点大，是否为正常现象？

### 你期望的结果

列表项之间的行距不大

### 问题复现的步骤

1. 输入列表代码
2. 编译后观察生成的PDF

### 最小可复现用例或者截图

编译以下内容：
```latex
这是第一个自然段。

这是第二个自然段
\begin{enumerate}
  \item 第一项
  \item 第二项
\end{enumerate}
```

![图片](https://user-images.githubusercontent.com/22538534/232122599-88ae425e-3b87-4154-906a-c8edabfdbf8c.png)

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2023

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
我倾向于认为这不是一个 Bug 
![image](https://user-images.githubusercontent.com/16451516/232176240-7c30ab8f-f87a-4366-8ccd-626b89fde19e.png)

但是改变行距确实也改变了 item 之间的间距——这和 Word 文档的行为不太一致。

![image](https://user-images.githubusercontent.com/16451516/232176678-123f8f22-42ea-4eda-93e2-c9ed4f08d538.png)

不知道 Word 文档的行为是你所期望的吗？

**Comment by fky2015** [comment]
但是如果一项的内容过多，反而保持现在的样式会更美观：

![image](https://user-images.githubusercontent.com/16451516/232178139-0e89e0a1-6a63-4d75-94e0-f932ca0607df.png)

**Comment by fky2015** [comment]
目前比较建议的方法，在需要取消多于间距的列表环境中使用`nosep`：

```
\begin{itemize}[nosep]
  \item ABC
  \item DEF
\end{itemize}
```

**Comment by c-my** [comment]
感谢回复，`[nosep]`的确可以取消多余间距，在一些情况下密集一点更协调。

总之，再次感谢您的认真回复！

**Comment by fky2015** [comment]
具体配置可以参考 `enumitem` 宏包手册。

如果有相关问题，可以再次开启次问题。
