### ISSUE TITLE
参考文献 乱了

### ISSUE THREAD

**Issue by gusgus3** [BITNP/BIThesis#294]
### 发生了什么？

参考文献顺序有问题
程序里面默认先所有article类写才写出来其他类。可以参考文献里面不一定前面都是article类。

### 你期望的结果

希望参考文献顺序按照论文里面提到的顺序写（普通论文的参考文献一样的）

### 问题复现的步骤

就是如何参考文献顺序按照论文里面提到的顺序写

### 最小可复现用例或者截图

![image](https://user-images.githubusercontent.com/113343157/232287570-92685889-33a7-4890-85db-39c87d563b41.png)

这里第4个是article类，所以直接跟aiticle类在一起。第4应该在第3后面

### 操作系统或平台

None

### BIThesis 模板

paper-translation

> 当然，作为改进，我们可以删除上面的实例内容以减少歧义。

对，删除以后还是有问题。

**Comment by fky2015** [comment]
请尝试清空中间文件后重新编译。
如果还是出现此问题，请提供一个我们可以复现的最小用例。

**Comment by fky2015** [comment]
思来想去终于理解你的意思了。
请看一下 `misc/2_reference.tex` 文件尾部的注释内容：

https://github.com/BITNP/BIThesis/blob/5181d5a16c5e1d980abc905de8a2256c1fa282fe/templates/paper-translation/misc/2_reference.tex#L115-L116

**Comment by fky2015** [comment]
当然，作为改进，我们可以删除上面的实例内容以减少歧义。

**Comment by gusgus3** [comment]
![image](https://user-images.githubusercontent.com/113343157/233277522-615d03d7-fc5b-4711-b557-149632d46dec.png)
这张是 2_reference.tex 文件

![image](https://user-images.githubusercontent.com/113343157/233277980-0aa99ec7-1c53-412a-ba95-b37214e99c5c.png)
这张是写每个参考文献的信息

最后得到的参考文献是很乱了。

**Comment by gusgus3** [comment]
谢谢。

但是还是有问题。

**Comment by fky2015** [comment]
Please remove every `\printbiblography` in your `2_references.tex`.

And add `\printbibliography[heading=none]`:

```latex
\begin{bibprint}

  \printbibliography[heading=none]
  
\end{bibprint}
```

**Comment by gusgus3** [comment]
感谢大佬！！！

**Comment by fky2015** [comment]
Then I'm closing this issue as solved.

Feel free to re-open it or file another issue for any other problems.
