### ISSUE TITLE
[Bug]: 字体错误，Font shape `TU/FangSong(0)/m/sc' undefined (Font) using `TU/FangSong(0)/m/n' instead.

### ISSUE THREAD

**Issue by ccyousa** [BITNP/BIThesis#297]
### 发生了什么？

windows 10 + texlive 2022 + VSCode（Latexmk）
编译后提示：Font shape `TU/FangSong(0)/m/sc' undefined (Font)	using `TU/FangSong(0)/m/n' instead.
输出的PDF文件中所有涉及这种粗体的地方都不是正确的粗体格式（比如封面、答辩信息页）。

### 你期望的结果

希望能够正确编译粗体。

### 问题复现的步骤

不修改模板的情况下，直接编译就有这种bug。

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2022

### BIThesis 模板

graduate-thesis

### 日志信息

```shell
Font shape `TU/SimSun(0)/m/sc' undefined
(Font)	using `TU/SimSun(0)/m/n' instead.
```

**Comment by fky2015** [comment]
能否截图说明一下“不正确的粗体”和“正确的粗体”的区别？

**Comment by ccyousa** [comment]
![image](https://user-images.githubusercontent.com/34744812/232767033-3a7c3a9f-10d5-4e8f-9f37-869256989aca.png)
![image](https://user-images.githubusercontent.com/34744812/232767121-a911c5af-e6e8-4317-9a68-4f70054474a0.png)

第一张图是期望的（overleaf里的），第二张图是有字体提示的（VSCode里的）。
（说法不太严谨，刚看了word模板这里用的是普通黑体，没有加粗。
但是第一张图里确实比第二张图里粗了一点点，因为看不到具体什么字体格式，所以不确定TU/SimSun(0)/m/sc和TU/SimSun(0)/m/sc有没有本质区别。）

**Comment by fky2015** [comment]
明白你的意思了。实际上，学校要求的效果恰恰是图二：

1. 日志信息和您遇到的这个问题基本无关。
2. 学校 Word 中字体是**中易黑体**。
3. 图一中，Overleaf 使用的应该是 **Fandol 黑体**，因为 Windows 的**中易黑体是有版权的**。
4. 图二中，应该用的是正常的**中易黑体**。

不过由于中易黑体没有粗体的字重，所以不论是 Word 还是 LaTeX 都采用伪粗体的方式实现粗体，因此在粗细程度上会有细微差别。（当然，这与您遇到的问题暂时无关）

**Comment by ccyousa** [comment]
这就是说overleaf的反而不满足格式要求，VSCode这个正常。
（本以为/m/sc和/m/n是两种字体分支 造成的。

**Comment by ccyousa** [comment]
同学你好，我想再问一下，模板编译后正文和参考文献中，英文部分全部大写是什么原因造成的，怎么解决呢？
这些英文首字母正常高度，后继字母半高，而且全部大写。
![image](https://user-images.githubusercontent.com/34744812/233090584-3e4e7e52-0ed2-469b-899b-db8def7d0df4.png)

**Comment by fky2015** [comment]
我无法复现你的问题。需要你提供一个“可以复现的最小用例”。
请确认你有没有使用过 `\textsc` 之类的命令。

**Comment by ccyousa** [comment]
感谢，已解决。是命令：`\scshape` 造成的，虽然不明白它的作用域怎么扩大到了全文。
