### ISSUE TITLE
[Bug]: 一页之中只存在标题时不会发生自动换行

### ISSUE THREAD

**Issue by ZoroGH** [BITNP/BIThesis#298]
### 发生了什么？

![image](https://user-images.githubusercontent.com/67215466/233247892-be46f59c-09f0-425a-aadc-019217b61be8.png)

使用模板 **undergraduate-thesis** .

如上图，一个页面之中只有标题时不会自动换页，75行与76行内容没有自动换页。当然本文章还未完成，没有填充任何正文。

也许实际情况下不会出现这种问题？

### 你期望的结果

标题 Section 也应该换页。

### 问题复现的步骤

1. 创建一个新的chapter
2. 用`\section` `\subsection`  `\subsubsection`  填充整个页面。

### 最小可复现用例或者截图

```latex
\chapter{微型化音视频采集硬件平台设计及其实现}

\section{硬件平台框架}

\section{硬件平台需求分析与设计原则}
\subsection{需求分析}
\subsection{设计原则}

\section{核心板卡硬件设计方案}
\subsection{ZYNQ芯片}
\subsection{AD9361}
\subsection{时钟模块}
\subsection{电源模块}
\subsection{接口模块}

\section{核心板卡PCB设计}
\subsection{PCB结构设计}
\subsection{PCB布局布线}
\subsection{PCB实物板卡}

\section{扩展板卡硬件设计方案}
\subsection{视频采集模块}
\subsection{音频采集模块}
\subsection{存储模块}
\subsection{时钟模块}
\subsection{电源模块}
\subsection{接口模块}

\section{扩展板卡PCB设计}
\subsection{PCB结构设计}
\subsection{PCB布局布线}
\subsection{PCB实物图} % 3.6.3
\subsection{PCB实物图} % 3.6.4 
\subsection{PCB实物图} % 3.6.5
\subsection{PCB实物图} % 3.6.6
1234
\subsection{PCB实物图}
123
\section{本章小结}
```

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TeX Live 2022 

### BIThesis 模板

undergraduate-thesis

### 日志信息

```shell
艹，我刚发现 overfull \vbox 的 info，所以这不算一个bug
```

**Comment by fky2015** [comment]
那…我关了？
