### ISSUE TITLE
本科生论文模板中图片表格与上下文的间距过大

### ISSUE THREAD

**Issue by miniAtom** [BITNP/BIThesis#303]
### 发生了什么？

本科生论文模板中图片表格与上下文的间距过大，目前大概有接近两行的间距，希望可以修改到大约一行的间距。

![image](https://user-images.githubusercontent.com/75769380/233791012-a89e45c1-dd27-4c08-b3e0-9bee2e99976a.png)

### 你期望的结果

希望修改图片表格等浮动体与上下文的间距为1行左右的高度。

### 问题复现的步骤

无。

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TeXlive2022

### BIThesis 模板

paper-translation, undergraduate-thesis

**Comment by fky2015** [comment]
实际上考虑到行间距（两行之间的空白），目前的高度就是一行（文字+相邻两行文字间空白距离）左右的高度。

另外，确实没有办法百分之百还原 Word 所谓的一行间距高度。

**Comment by miniAtom** [comment]
【自动回复】来信已收到，十分感谢！

**Comment by fky2015** [comment]
一般来说这个地方不应该太过纠结，毕竟排版这种东西美观就好。

目前来说，如果你实在想要调整，可以在 `bithesis.cls` 中找到以下内容。

```
  \setlength{\intextsep}{1.80\baselineskip plus 0.2\baselineskip minus 0.2\baselineskip}
```

修改此处的 `1.80` 为更小的值即可。

但是这种浮动环境与周围文字的间距的决定因素比较复杂，因此不太适合做成接口暴漏给用户，也很难追求百分百还原 Word 样式。

**Comment by miniAtom** [comment]
好的，谢谢
