### ISSUE TITLE
\autoref 是否需要增加关于图和表的默认文字

### ISSUE THREAD

**Issue by ZoroGH** [BITNP/BIThesis#313]
### 发生了什么？

![image](https://user-images.githubusercontent.com/67215466/234273640-16113a57-4138-4077-987b-2cd50808df55.png)
![image](https://user-images.githubusercontent.com/67215466/234273654-d2c08986-2a79-4673-93fc-6f7d4e6d5650.png)

### 你期望的结果

\autoref{xxx}
--> 图xx，表xx

### 问题复现的步骤

-

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TeX Live 2022 

### BIThesis 模板

undergraduate-thesis

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/issues/38
