### ISSUE TITLE
\ref 和 \cite交叉引用的地方怎么设置为蓝色

### ISSUE THREAD

**Issue by Higher0** [BITNP/BIThesis#314]
### 发生了什么？

使用的硕士毕业论文模板BIThesis-graduate-thesis-v3.5.3，生成的PDF中交叉引用的地方虽然可以点击跳转，但是黑色跟其他文字一样不方便查看，如何改为蓝色？

### 问题复现的步骤

无

### 最小可复现用例或者截图

<img width="67" alt="1682694221949" src="https://user-images.githubusercontent.com/37284152/235183646-d935c0ab-9c7c-4cc8-9e5a-3dee9b871781.png">

### 操作系统或平台

Overleaf

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
下一个版本将提供 `misc/hideLinks` 选项用于控制这个行为。
