### ISSUE TITLE
[Bug]: Windows 下宋体粗体变为黑体 与 目录缩进 问题

### ISSUE THREAD

**Issue by ccyousa** [BITNP/BIThesis#321]
### 发生了什么？

1. 硕士学位论文格式要求： “关键词”宋体小四加粗，现在应该是黑体。
2. 目录缩进（一、二级标题）应该分别是两个字符和四个字符，但现在是一个和两个字符。
3. 感觉图题和下一行正文之间的行间距有点大，但是看不出来是几倍行距。
4. 另外想问一下，latex 是不是会根据排版自动调整部分节标题的上下行距，同一等级的节标题有的地方上间距很大，有的就小。
5. \paragraph 命令的上下间距也是类似，比一级节标题的还宽。

### 你期望的结果

1. 关键词 三字的字体正确。
2. 目录缩进宽度和word一致。

### 问题复现的步骤

- 

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2022

### BIThesis 模板

master-thesis

**Comment by fky2015** [comment]
1. 可以参考 https://github.com/xiaoyao9933/UCASthesis/issues/14

首先需要说明的是，macOS 和 Linux 下的粗体宋体都是正常的。

解决方法有几个：
- 继续使用黑体。
- 在 `documentclass` 下面加上 `\setCJKmainfont{simsun.ttc}[AutoFakeBold] ` （仅限 Windows 平台）。
- 安装所有 adobe 的字体，在 `documentclass` 里面传入 `ctex={fontset=adobe},`

2. 确实，但是我最近实习了，不一定有时间修复。
3. 对，是弹性距离。为了排版美观。一般空白大说明你文字太少了。
4. 默认确实是这样的，之后可能考虑统一减小一下；现在只能靠用户了。

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/releases/tag/v3.6.0-beta-1

**Comment by ccyousa** [comment]
新的release typo并没有改过来。

**Comment by fky2015** [comment]
改过了来，中午又重新发过一个（同样的）版本。请重新下载一下。

**Comment by fky2015** [comment]
等周末有机会碰到 Windows 的电脑以后，我预期会在模板里增加一个关于开启伪粗体的注释。届时，本 Issue 将关闭。

**Comment by fky2015** [comment]
fixed by: #335
