### ISSUE TITLE
本科生论文章节间出现空白页

### ISSUE THREAD

**Issue by CheeseOkra** [BITNP/BIThesis#323]
### 发生了什么？

多个章节从偶数页开始，其前的奇数页被跳过，出现空白页

### 你期望的结果

不需要空白页

### 问题复现的步骤

新\chapter{}只要从奇数页开始就会出现这个问题

### 操作系统或平台

Windows

### BIThesis 模板

undergraduate-thesis

**Comment by fky2015** [comment]
请认真阅读手册和 main.tex 关于 twoside 的说明。

**Comment by CheeseOkra** [comment]
我的实际情况是 在第二章和第三章之间出现空白页，即第13页；而第五章可以从奇数页35页开始。也就是说，这种空白页问题只出现了一次，其他情况均是正常的。
我尝试过删去twoside，也尝试过将twoside设置false，但是没有改变。
另外这种情况出现在编译参考文献后，在没有编译ref.bib文件之前页面连续而且没有出现空白页。
我重新下载了模板并重新填写了内容，但是没有改变。
求教，非常感谢。

**Comment by fky2015** [comment]
我最近在实习，空闲时间很少。如果可以的话，请提供一个可以复现的最小用例。（删去个人隐私内容）

**Comment by fky2015** [comment]
> 请认真阅读手册和 main.tex 关于 twoside 的说明。twoside 是为了方便而默认开启的；删去就可以。

我这里说的是错误的：本科生模板默认没有开启 twoside。因此不应该出现空白页面。

然而，我没有办法复现出你的问题。我这里的页面均是正常的。因此如果想要继续推动这个事情，需要你提供用于复现的完整代码。

**Comment by fky2015** [comment]
一般这种奇怪的问题都跟中间编译结果有关，清理了就好。
