### ISSUE TITLE
[Bug]: macOS 下编译后，查重参考文献大面积标红

### ISSUE THREAD

**Issue by Zeqiang-Lai** [BITNP/BIThesis#326]
### 发生了什么？

目前怀疑是 macos 系统编译下导致的，有同学用同样模板，使用windows编译暂无问题。可以帮忙确认一下问题吗？

![image](https://user-images.githubusercontent.com/26198430/237003915-0500660a-4d9b-4efb-84f0-c0c60bfb4c48.png)

### 问题复现的步骤

无

### 操作系统或平台

macOS

**Comment by fky2015** [comment]
抱歉，查重的原理我并不清楚，也没有能力和时间进行调试。

**Comment by ZoroGH** [comment]
@Zeqiang-Lai  [查重](https://zhuanlan.zhihu.com/p/617928789)
在windows下貌似没有出现乱码的情况，不知道MacOS下如何

**Comment by Zeqiang-Lai** [comment]
确实是知乎说的这个问题，参考文献复制出来是乱码。

https://github.com/BIT-thesis/LaTeX-template 旧模板没有这个问题。

**Comment by ccyousa** [comment]
渲染正常，复制是乱码的话，可能是无意中替换为了非通用的字体。

**Comment by fky2015** [comment]
那么可以尝试安装 windows 字体后，通过切换 `\documentclass[..., ctex={fontset={windows}}]` 来切换字体。

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/discussions/317 目前感觉 macOS 遇到这个问题挺多的。

**Comment by fky2015** [comment]
可否帮忙通过 PDF 阅读器看一下，字体有没有嵌入子集？（尤其是华文仿宋）

**Comment by Zeqiang-Lai** [comment]
请问要怎么看呢

**Comment by fky2015** [comment]
https://supportcommunity.zebra.cn/s/article/000022734

**Comment by fky2015** [comment]
> 确实是知乎说的这个问题，参考文献复制出来是乱码。

我确认一下，你是用 wps 复制出来发现是乱码？如果不是的话还请告知一下复现步骤

**Comment by Zeqiang-Lai** [comment]
我没有adobe pdf，wps。我用的macos上的预览和pdf expert复制出来是乱码。

**Comment by fky2015** [comment]
那看起来并不是人人都会遇到这个问题，我这边用「预览」复制出来是正常的。

**Comment by fky2015** [comment]
或许可以尝试一下更新 TexLive

**Comment by Zeqiang-Lai** [comment]
可能还是字体的问题吧？你的电脑是不是装了windows字体

macOS 13.3.1

TeX 3.141592653 (TeX Live 2022)
kpathsea version 6.3.4
Copyright 2022 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.

**Comment by fky2015** [comment]
我没有额外安装过任何字体。我这边现在走的应该是[宋体-黑]。看了一下你的应该也是。

和你 mac 版本一样，TeXLive 我是新装的。

**建议首先升级到 2023。**

然后尝试 `\documentclass[..., ctex={fontset={macnew}}]` （感觉关系不大）

**Comment by Zeqiang-Lai** [comment]
可以，2023 能正常复制了，建议在readme写个提示

**Comment by fky2015** [comment]
> 可以，2023 能正常复制了，建议在readme写个提示

如果你有时间的话，能否麻烦你帮忙完成这个事情？GitHub 可以通过网站嵌入的 editor 直接编辑文本的。

**Comment by Zeqiang-Lai** [comment]
可以的，发PR了

**Comment by fky2015** [comment]
Fixed by: #331
