### ISSUE TITLE
本科毕设模板更新（2023年3月）

### ISSUE THREAD

**Issue by psq512** [BITNP/BIThesis#332]
您好，今天我们收到了本科毕设模板的更新，请问在此模板中应如何修改？

[关于2023届本科毕业设计（论文）模板及打印装订要求.zip](https://github.com/BITNP/BIThesis/files/11451623/2023.zip)

**Comment by fky2015** [comment]
感谢你的提醒。三月份前后，我已经从教务部老师那里拿到过此文件。目前的模板已经符合最新的要求。如果有任何具体问题，可以通过 Issues 反馈。
