### ISSUE TITLE
[Bug]: 参考文献排版格式问题（本科毕设模板）

### ISSUE THREAD

**Issue by MozerWang** [BITNP/BIThesis#343]
### 发生了什么？

我参考文献用的是bibtex格式，对于参考文献的默认格式，没有做任何改动，但是最终参考文献遇到以下问题：
<img width="385" alt="image" src="https://github.com/BITNP/BIThesis/assets/80452608/c4d39bc4-c072-49e4-853f-23ae73f951b7">
问题1.文献类型与标号对齐了；
问题2.文献的附加信息用“//”符号隔开了

### 你期望的结果

我希望
1.文献类型不要跟标号对齐
2.附加信息用In连接而不是“//”

### 问题复现的步骤

我把图中四个参考文献贴上，不做任何改动直接导出，就会有这样的排版问题

### 最小可复现用例或者截图

@inproceedings{chen-etal-2017-reading,
    title = "Reading {W}ikipedia to Answer Open-Domain Questions",
    author = "Chen, Danqi  and
      Fisch, Adam  and
      Weston, Jason  and
      Bordes, Antoine",
    booktitle = "Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
    month = jul,
    year = "2017",
    address = "Vancouver, Canada",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/P17-1171",
    doi = "10.18653/v1/P17-1171",
    pages = "1870--1879"}

@inproceedings{Green:1961,
  added-at = {2007-12-14T02:39:31.000+0100},
  author = {Green, B.F. and Wolf, A.K. and Chomsky, C. and Laughery, K.},
  biburl = {https://www.bibsonomy.org/bibtex/27cc889a7269107b71e0bc19fa91497d2/diego_ma},
  booktitle = {Proceedings Western Computing Conference},
  interhash = {d28ec67bb5cde621b41ccfb3796b5838},
  intrahash = {7cc889a7269107b71e0bc19fa91497d2},
  keywords = {question_answering},
  pages = {219-224},
  timestamp = {2007-12-14T02:39:31.000+0100},
  title = {BASEBALL: An automatic question answerer},
  volume = 19,
  year = 1961
}
@misc{ouyang2022training,
      title={Training language models to follow instructions with human feedback}, 
      author={Long Ouyang and Jeff Wu and Xu Jiang and Diogo Almeida and Carroll L. Wainwright and Pamela Mishkin and Chong Zhang and Sandhini Agarwal and Katarina Slama and Alex Ray and John Schulman and Jacob Hilton and Fraser Kelton and Luke Miller and Maddie Simens and Amanda Askell and Peter Welinder and Paul Christiano and Jan Leike and Ryan Lowe},
      year={2022},
      eprint={2203.02155},
      archivePrefix={arXiv},
      primaryClass={cs.CL}
}
@misc{openai2023gpt4,
      title={GPT-4 Technical Report}, 
      author={OpenAI},
      year={2023},
      eprint={2303.08774},
      archivePrefix={arXiv},
      primaryClass={cs.CL}
}

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

Texlive 2023

### BIThesis 模板

undergraduate-thesis

**Comment by MozerWang** [comment]
附加一个信息：
已经设置了 \printbibliography[heading=none]

**Comment by fky2015** [comment]
问题一：请参考 bithesis.pdf 中参考文献对齐的选项。
问题二：引入 biblatex 的选项中加入 `gbpunctin=false` ，详细用法请在 https://ctan.math.illinois.edu/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf 中 。不过需要说明的是，使用 `//` 才是符合国标的做法，详见 http://journal.ustc.edu.cn/uploadfile/yjsjy/20161108/GB%20T%207714-2015%E4%BF%A1%E6%81%AF%E4%B8%8E%E6%96%87%E7%8C%AE-%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E8%91%97%E5%BD%95%E8%A7%84%E5%88%99.pdf。

**Comment by MozerWang** [comment]
问题一: 不好意思我表述有误，您可能理解错我的意思了，我不是要让参考文献缩进，而是不要让文献类型与编号对齐，参考文献仍然保持不缩进。我看学校模板的意思是不能让参考文献缩进的。
问题二：谢谢大佬！

**Comment by fky2015** [comment]
问题一：你这个对齐了是因为正常换行吧...不然它应该出现在什么位置呢？

**Comment by MozerWang** [comment]
谢谢解答 辛苦维护了！
