### ISSUE TITLE
支持“北京理工大学”水印

### ISSUE THREAD

**Issue by wuzirui** [BITNP/BIThesis#350]
### 发生了什么？

计算机学院要求外文翻译报告使用带有“北京理工大学”水印，如图所示：
![image](https://github.com/BITNP/BIThesis/assets/7344146/d68935bd-e9e2-462c-9e4a-2bb4d2126b21)

### 问题复现的步骤

无

### 操作系统或平台

None

### BIThesis 模板

paper-translation

**Comment by wuzirui** [comment]
- 提供一个可行的解决方案供参考：
-  - 将 [background.pdf](https://github.com/BITNP/BIThesis/files/11583990/background.pdf) 放在 `paper-translation/images/` 中，并使用下面的代码

```latex
\newcommand\BackgroundPicture{%
  \put(0,0){%
    \parbox[b][\paperheight]{\paperwidth}{%
      \vfill
      \centering%
      \includegraphics[width=\paperwidth]{paper-translation/images/background.pdf}
      \vfill
    }}}

% 文档开始
\begin{document}
\AddToShipoutPicture{\BackgroundPicture}
....
```

**Comment by fky2015** [comment]
请问计算机学院是指定了水印的样式（如图所示），还是只要求有水印即可？

**Comment by wuzirui** [comment]
> @wuzirui 请问计算机学院是指定了水印的样式（如图所示），还是只要求有水印即可？

需要按照该格式加水印。这个pdf是从官方word里面直接导出的

**Comment by fky2015** [comment]
要么就在文献翻译的模板里面写一个注释，指向此 issue。要么就干脆直接把代码加成注释。

如果你有兴趣的话也欢迎 PR。

**Comment by Aaron-Gp** [comment]
如果需要调整水印的透明度可以参考这个链接：https://tex.stackexchange.com/questions/86500/includegraphics-set-image-opacity

**Comment by Aaron-Gp** [comment]
另：计院今年（2025）要求本科毕设的开题报告、中期报告、文献翻译均需在系统填写，不能以附件方式上传，大抵是只能用word编辑了
