### ISSUE TITLE
[Bug]: 关于研究生学位论文封面的字段问题

### ISSUE THREAD

**Issue by ccyousa** [BITNP/BIThesis#357]
### 发生了什么？

根据word模板和旧版latex，图书馆论文， “申请学位级别” 应为 “申请学位” 
关于 “学科专业”，emmm 值得探讨。。word和旧版latex似乎也不一样。。。

另外：
有可能使得英文摘要部分实现 单词的自动截断（即长单词根据短杠分为两部分） 以自动换行？

### 问题复现的步骤

直接编译

### 操作系统或平台

None

**Comment by fky2015** [comment]
> 根据word模板和旧版latex，图书馆论文， “申请学位级别” 应为 “申请学位”

根据《北京理工大学研究生学位论文撰写规范》，确实应当为“申请学位级别”。

不过这个事情倒是不用太担心，很快这些常量也会支持自定义配置。用户想怎么改就怎么改就是了。（学校的版本混乱，心累）

> 有可能使得英文摘要部分实现 单词的自动截断（即长单词根据短杠分为两部分） 以自动换行？

有道理。现在英文模板已经支持。中文模板反而添加了额外的语句禁用了。如果你有兴趣也可以研究一下，删掉约束即可，欢迎 PR。

**Comment by YDX-2147483647** [comment]
> 很快这些常量也会支持自定义配置

请问能否大约估计一下什么时候？几天后，几周后，还是几月后？

**Comment by fky2015** [comment]
几周后吧，我目前每周末才有时间写代码。

**Comment by fky2015** [comment]
可以参考现在的 `consts` 选项。之后内部的常量都会通过这种方式进行配置。
