### ISSUE TITLE
[Bug]: 模板注释中关于封面字段的描述与实际不符

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#361]
### 发生了什么？

https://github.com/BITNP/BIThesis/blob/87cb685f0c6d58e641cb588893a03778a9c258c7/templates/undergraduate-thesis/main.tex#L43-L45

实际试下来（我主要试了学号）如下。

- 正常设置`studentId = 11xxxxxxxx`——正常`学 号： 11xxxxxxxx`
- 删除——显示默认值`学 号： 3120211xxx（示例）`
- 设为空`studentId = {}`——不显示

### 你期望的结果

注释与实际相符，或者实际与注释相符。

### 问题复现的步骤

1. 编译 templates/undergraduate-thesis/main.tex。
2. 按前面描述修改`\BITSetup`，重新编译，观察封面。

### 最小可复现用例或者截图

MWE：现在[仓库中的版本](https://github.com/BITNP/BIThesis/blob/87cb685f0c6d58e641cb588893a03778a9c258c7/templates/undergraduate-thesis/main.tex)即可。

![图片](https://github.com/BITNP/BIThesis/assets/73375426/0e352eb4-f80b-4512-bbc9-a1f9bc6870ba)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/be9793c3-5a68-4abc-ae2b-38de9d0d8735)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/b456f61f-7e0c-473e-9bd8-51cf49c17026)

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TeX Live 2023

### BIThesis 模板

undergraduate-thesis

**Comment by fky2015** [comment]
应该是只有「校外指导教师」符合这个描述。
