### ISSUE TITLE
[Bug]: 手册中 Note 后的“本”变红、强调

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#375]
### 发生了什么？

请看图，这是`texdoc bithesis`第11页。

![](https://github.com/BITNP/BIThesis/assets/73375426/5f988490-b73b-4b61-9b62-6cd4d279cf05)

大概在这里。

https://github.com/BITNP/BIThesis/blob/6e72dad989ccd85c5be6cfe3ccf2ebf7c7fee8c2/bithesis-doc.tex#L446-L449

### 你期望的结果

“本”和后面的字一样。

（我不太确定，可能目前格式特意如此？）

**Comment by fky2015** [comment]
不是预期的

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis/blob/6e72dad989ccd85c5be6cfe3ccf2ebf7c7fee8c2/bithesis.dtx#L3958-L3959

是不是要 Note 变红，后面一段全部强调？

**Comment by fky2015** [comment]
应该是的。
