### ISSUE TITLE
请问UI是什么框架呀

### ISSUE THREAD

**Issue by Leng-bingo** [BITNP/BIThesis#398]
### 发生了什么？

请问UI是什么框架呀

### 你期望的结果

请问UI是什么框架呀

### 问题复现的步骤

请问UI是什么框架呀

### 操作系统或平台

None

**Comment by YDX-2147483647** [comment]
呃，能否具体解释一下问题？[BITNP/BIThesis-wiki 在线文档](https://github.com/BITNP/BIThesis-wiki/) 使用 VitePress 构建；而 LaTeX 模板从[`bithesis.dtx`](https://github.com/BITNP/BIThesis/blob/main/bithesis.dtx)编译，似乎用户界面是使用者的键盘？

**Comment by YDX-2147483647** [comment]
`\BITSetup`的定义如下，其中`\DeclareDocumentCommand`是 LaTeX3 的`xparse`提供的。

https://github.com/BITNP/BIThesis/blob/0d2315f1f91f26bd9ecf686040f46085f48f9672/bithesis.dtx#L1999-L2007

**Comment by YDX-2147483647** [comment]
`@_@`
