### ISSUE TITLE
Feature Request: 希望提供一个可自定义的变量命令用于声明一些常量

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#405]
在论文写作中，经常会使用一些重复但又有可能更改的词语。这些词语被大量使用以后，一旦想要更改，就会很麻烦。比如以下场景：

1. 小明在文章中大量使用了“机械手臂”这个词语。
2. 小明希望修改“机械手臂”为“机械臂”。
3. 需要进行全局替换，并防止非预期的替换发生。

如果可以有以下的特性：

1. 在 main.tex 中使用

```latex
\BITSetup{
  % ...
  terms = {
    MA = "机械手臂"
  }
}
```

2. 在正文中使用 `\terms{MA}`

则在将来可以快速进行替换。

**Comment by YDX-2147483647** [comment]
呃，这种方法与自己定义命令相比有什么优势呢？

```latex
\newcommand*{\termsMA}{机械手臂}
```

```latex
\termsMA 是什么？
```

**Comment by fky2015** [comment]
手工定义也是可以的，那么建议我们的模板提供一下这样的用例

**Comment by YDX-2147483647** [comment]
好吧；放到 [📃 LaTeX 学习与使用资源 | BIThesis](https://bithesis.bitnp.net/guide/resources.html)，还是放到`*.tex`里呢？

[补充一些有用的学习资源 · Issue #39 · BITNP/BIThesis-wiki](https://github.com/BITNP/BIThesis-wiki/issues/39)

**Comment by fky2015** [comment]
感觉都可以。
