### ISSUE TITLE
[Bug]: 盲审时文献列表中有多余的“等”或“et al.”

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#410]
### 发生了什么？

如果`reference/pub.bib`中有某项`author`数量超过`main.tex`中`publications/maxbibnames`（默认为3），那么靠后的作者会被省略。

生成盲审版时，这会变成`第二作者, et al.`。

### 你期望的结果

只有`第二作者`。

### 缓兵之计

生成盲审版时手动把`maxbibnames`调大（比如123），这样根本不省略，就没问题了。

### 问题复现的步骤

`main.tex`:

```diff
- \documentclass[type=master,twoside]{bithesis}
+ \documentclass[type=master,twoside,blindPeerReview=true]{bithesis}
```

`reference/pub.bib`:

```diff
-  author = {张三 and 李杰 and 罗运军},
+  author = {张三 and 李杰 and 罗运军 and 汪淼},
```

### 最小可复现用例或者截图

![图片](https://github.com/BITNP/BIThesis/assets/73375426/5ddb2db9-32cd-4b9b-a1a9-c2873a5c69c9)

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TeXLive 2023

### BIThesis 模板

graduate-thesis

---

群里Z同学遇到的。

### 可能的解决方案

```diff
        % 如果覆盖的是英文作者，不修改此项的话，会在最开始有空格。
        \DeclareDelimFormat{bibnamedelimd}{}

+       % 如果作者太多（超出maxbibnames）而被截断，不修改的话，会多余逗号、“等”云云。
+       % 故设置标点来去掉逗号，
+       \DeclareDelimFormat[bib,biblist]{andothersdelim}{“AND-OTHERS-DELIM”}
+       % 并设置本地化字符串来去掉“等”。
+       \setlocalbibstring{andothers}{“AND-OTHERS”}
+       \setlocalbibstring{andotherscn}{“AND-OTHERS-CN”}
+       % 注意我们仍然尊重maxbibnames。虽然这可能导致完全不显示作者（这时正常做法是改maxbibnames），但不尊重的话会导致开关盲审时效果不同，可能引起困惑。
      }
```

**Comment by YDX-2147483647** [comment]
> 感觉这个不太好修
>
> 只能打个补丁：开启盲审模式的时候`maxbibnames`自动调成一个比较大的值

**Comment by YDX-2147483647** [comment]
西文的如果超出，还会只剩`et al.`。

![](https://github.com/BITNP/BIThesis/assets/73375426/2b7dbc3a-953b-4d87-9e04-ab3be430a8f9)

```diff
-  author = "John Doe and San Zhang",
+  author = "John Doe and San Zhang and White Ice and AAA",
```

**Comment by hushidong** [comment]
后面biblatex-gb7714-2015会增加gbnoothers选项，控制不让其输出。
若是在publications环境中局部调整，则设置`\settoggle{bbx:gbnoothers}{true}`即可。
