### ISSUE TITLE
原论文模板[原创性声明]部分更新

### ISSUE THREAD

**Issue by ljcBIT** [BITNP/BIThesis#417]
### 发生了什么？

《北京理工大学研究生学位论文答辩细则》《研究生论文模板》已做修订并在研院网站发布，自2024年3月21日起执行，原相关文件同时废止，原论文模板同时更新。
论文模板（模板修订学位论文原创性声明，其他不变）：
- [文件下载\_研究生学位论文模版\_北京理工大学研究生院](https://grd.bit.edu.cn/xwgz/xwgz2/wjxz_xwgz/b119746.htm)
- [规章制度\_北京理工大学研究生学位论文答辩细则\_北京理工大学研究生院](https://grd.bit.edu.cn/xwgz/xwsy/gzzd_xwsy/126883c0fcfd47a0aec6b496674b2bc9.htm)

**Comment by fky2015** [comment]
目前已经有同学帮忙修改了「研究成果声明」和「关于学位论文使用权的说明」这两个部分，我们将在 3.6.4 版本交付这一改动。

**Comment by fky2015** [comment]
更正一下，是 3.7.0 版本。
