### ISSUE TITLE
[Bug]: Overleaf的研究生论文模版格式与最新版不一致

### ISSUE THREAD

**Issue by ZhuHandong** [BITNP/BIThesis#422]
### 发生了什么？

Overleaf的研究生论文模版，在声明部分与官方最新版（3.20）不一致，而且横竖标题附近有空白页

### 你期望的结果

与官方论文格式一致

### 问题复现的步骤

点击研究生论文模版旁边的open overleaf即可看到不一致

### 最小可复现用例或者截图

无

### 操作系统或平台

Windows

### BIThesis 模板

master-thesis

### 日志信息

```shell
无
```

**Comment by fky2015** [comment]
问题一：因为目前还没有完成 3.7.0 在 Overleaf 的上传工作，进度可见 https://github.com/BITNP/BIThesis/issues/420。主要还是因为维护者也并非 7x24 小时在岗，所以需要抽个人休息时间完成。这个还请谅解。像这种不影响论文写作、可以平滑升级且暂时不紧急的升级，我们会优先合入代码，然后稍缓完成各平台的更新。

问题二：在 main.tex 上方的注视里面已经对 twoside 参数的含义说的很清楚了：因为在论文打印的时候通常是双面打印的，而封面这种内容需要在奇数页，因此我们会自动为你添加偶数空白页。这个是相比 Word 多出来的功能，而不是 Bug。想关掉 twoside 可以选 false。

不知道能否解决你的问题？期待你的回复。

**Comment by ZhuHandong** [comment]
已充分解决我的疑问，非常感谢！！

**Comment by YDX-2147483647** [comment]
https://cn.overleaf.com/read/nbgpkpgnggpc#e83ead

↑ https://github.com/BITNP/BIThesis-wiki/commit/21fe2d2d83d4938017bf0e6d8e9150a99e64ffe8 刚刚更新了Overleaf链接（v3.7.0），不过[网站](https://bithesis.bitnp.net/guide/preface.html)上可能要再等等。

如果想更新Overleaf项目，从 [Releases](https://github.com/BITNP/BIThesis/releases) 下载`bithesis.cls`，覆盖原有的即可。

然后既然没问题了，我就把这个议题关了吧。

**Comment by ZhuHandong** [comment]
非常感谢您们的帮助！问题已解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月23日 13:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BITNP/BIThesis] [Bug]: Overleaf的研究生论文模版格式与最新版不一致 (Issue #422) |

https://cn.overleaf.com/read/nbgpkpgnggpc#e83ead

↑ ***@***.*** 刚刚更新了Overleaf链接（v3.7.0），不过网站上可能要再等等。

如果想更新Overleaf项目，从 Releases 下载bithesis.cls，覆盖原有的即可。

然后既然没问题了，我就把这个议题关了吧。
