### ISSUE TITLE
学校模板更新 求助新模板

### ISSUE THREAD

**Issue by Crustaaaaacean** [BITNP/BIThesis#427]
### 发生了什么？

老板 模板更新了 求助！新模板word地址-> https://grd.bit.edu.cn/xwgz/xwgz2/wjxz_xwgz/b119746.htm 

### 问题复现的步骤

编译一下

### 最小可复现用例或者截图

![Picture1](https://github.com/BITNP/BIThesis/assets/48672831/a2655a1e-c9ec-45cc-8320-a83057e73435)

### 操作系统或平台

None

**Comment by Crustaaaaacean** [comment]
研究生论文模板更新

**Comment by fky2015** [comment]
已经在 3.7.0 更新。
