### ISSUE TITLE
本科外文翻译（paper-translation）的页眉

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#431]
之前的讨论：https://github.com/BITNP/BIThesis/discussions/396#discussioncomment-8011812

> 刚才信息学院教学干事通知说页眉是“北京理工大学本科生毕业设计（论文）”，不能改成“……外文翻译”。如果需要更改，请编辑`main.tex`。
>
> ```diff
>   style = {
> -   % head = {自定义页眉文字}
> +   head = {北京理工大学本科生毕业设计（论文）}
>   }
> ```

今天教学干事反馈，专门说有几位同学页眉错误，应为“北京理工大学本科生毕业设计（论文）”。如果其它学院也这样，恐怕需要修改模板。

**Comment by fky2015** [comment]
这个问题我们的教务部没有更新么？

**Comment by YDX-2147483647** [comment]
> 我们的教务部网站提供的模板没有更新么？

教务部的通知都放在知网毕设系统上，我不确定是否所有学院一样。教务部没有单独提供外文翻译正文模板（只有封面，而封面无页眉），《书写要求》（如下）也没有明文规定。

> 外文翻译5000字左右，内容与毕业设计（论文）题目有关。外文原文用A4纸打印或复印，中文翻译用A4纸打印，文档格式要求参考“毕业设计（论文）文档格式要求”。装订顺序为：外文翻译封面→外文原文→中文翻译。

**Comment by fky2015** [comment]
OK，那我们可以考虑默认改为北京理工大学本科生毕业设计（论文）。

**Comment by YDX-2147483647** [comment]
嗯，我打算问问别的学院同学，确定了再改。

**Comment by YDX-2147483647** [comment]
如上条消息，问的差不多了，结论是还不确定，答辩完再看看。

**Comment by fky2015** [comment]
说实话，外文翻译不会有出了自己以外的任何人看。

**Comment by Jixiang-Wang-BIT** [comment]
哥们儿，请问有没有带水印的版本

**Comment by YDX-2147483647** [comment]
@Jixiang-Wang-BIT 

https://github.com/BITNP/BIThesis/blob/959fb1c75a0dc3edc974ad8c47004bfc8698399f/templates/undergraduate-thesis/main.tex#L97-L100

https://github.com/BITNP/BIThesis/issues/350#issuecomment-1565974141

// 建议以后去 issue 或 discussion 新建。

**Comment by fky2015** [comment]
这个问题最近有什么进展么？（我听说已经有本科生答辩了）

**Comment by YDX-2147483647** [comment]
是有一部分人答辩了，不过大约都还没交归档材料；[成绩录入6月6日才截止](https://jwb.bit.edu.cn/tzgg/026420854e704c86a2790948f6dc7034.htm)。

**Comment by fky2015** [comment]
Ping，感觉以注释的形式在 `style / head`  标明就好？

**Comment by YDX-2147483647** [comment]
知网系统导出的空文档（就是大家都不用的那个Word文档）上，页眉是“……外文翻译”。

- 信息：忽略系统导出的东西，我们只用同学上传的附件。已经通知将页眉改成“北京理工大学本科生毕业设计（论文）”。
- 车辆：没提什么要求。
- 光电：（稍晚些回复）
- 计算机：没有通知这个细节。
- 网安：没有提这事儿了。

那我加一下注释吧。
