### ISSUE TITLE
[Bug]: "研究成果清单"中成果排列顺序与引用顺序不符

### ISSUE THREAD

**Issue by zxd52csx** [BITNP/BIThesis#443]
### 发生了什么？

使用2023版本在线XeLaTeX编译工具(TexPage)编辑，在reference/pub.bib中添加了多个成果，并在misc/4_pub.tex中写入下列代码：

```latex
\addpubs{my1,my2,my3, my4}
\printbibliography[heading=none, category=mypub, resetnumbers=true] 
```

编译后研究成果清单中的成果顺序混乱，不是按照my1, my2, my3, my4 的顺序显示的

### 问题复现的步骤（或者截图）

None

### 操作系统或平台

None

### LaTeX 发行版以及发行年份

XeLaTeX2023

### BIThesis 模板

graduate-thesis

**Comment by fky2015** [comment]
解决方法请见 https://github.com/BITNP/BIThesis/discussions/407

看来后续为了防止用户感到疑惑，我们需要在 pub.tex 中提供相关说明

**Comment by YDX-2147483647** [comment]
#407 是微调顺序；如果要完全推翻日期顺序，按引用顺序来，编辑`main.tex`，找到`\BITSetup{…}`中的`publications`，加上`sorting = false`就好 。

![图片](https://github.com/BITNP/BIThesis/assets/73375426/f1341203-bbd9-4ee0-996f-b7ff0d0c3719)

**Comment by fky2015** [comment]
感谢补充（由于时间过于久远，已经记不清自己写的代码逻辑了。我就说我记得是能自定义排序的。

**Comment by zxd52csx** [comment]
感谢回复~

**Comment by zxd52csx** [comment]
回复很好地解决了问题
