### ISSUE TITLE
[Bug]: 使用algorithm2e宏包时，标题仍然显示为英文「Algorithm」

### ISSUE THREAD

**Issue by RemnantCloude** [BITNP/BIThesis#454]
### 发生了什么？

问题如题所示，似乎是因为只对algorithm宏包做了适配？

### 问题复现的步骤（或者截图）

我尝试的代码如下所示：
**引入宏包**
`\usepackage[linesnumbered,ruled,vlined]{algorithm2e}`

**正文代码**
```latex
\begin{algorithm}

  \SetKwData{Left}{left}\SetKwData{This}{this}\SetKwData{Up}{up} \SetKwFunction{Union}{Union}\SetKwFunction{FindCompress}{FindCompress} \SetKwInOut{Input}{输入}\SetKwInOut{Output}{输出}

  \Input{A bitmap $Im$ of size $w\times l$}
  \Output{A partition of the bitmap}
  \BlankLine

  \emph{special treatment of the first line}\;
  \For{$i\leftarrow 2$ \KwTo $l$}{
    \emph{special treatment of the first element of line $i$}\;
    \For{$j\leftarrow 2$ \KwTo $w$}{\label{forins} \Left$\leftarrow$\FindCompress{$Im[i,j-1]$}\;
      \Up$\leftarrow$ \FindCompress{$Im[i-1,]$}\;
      \This$\leftarrow$ \FindCompress{$Im[i,j]$}\;
      \If(\tcp*[h]{O(\Left,\This)==1})
      {\Left compatible with \This}{\label{lt}
        \lIf{\Left $<$ \This}{\Union{\Left,\This}}
        \lElse{\Union{\This,\Left}} }
      \If(\tcp*[f]{O(\Up,\This)==1}){\Up compatible with
        \This}{\label{ut}
        \lIf{\Up $<$ \This}{\Union{\Up,\This}}
        \tcp{\This is put under \Up to keep tree as flat as possible}\label{cmt} \lElse{\Union{\This,\Up}}\tcp*[h]{\This linked to \Up}\label{lelse}
      }
    }
    \lForEach{element $e$ of the line $i$}{\FindCompress{p}}
  }
  \caption{disjoint decomposition}
  \label{algo_disjdecomp}
\end{algorithm}
```

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

TexLive 2023

### BIThesis 模板

graduate-thesis

**Comment by YDX-2147483647** [comment]
我可以复现这个问题，我查查怎么办。

> 只对algorithm宏包做了适配？

#445 调整的`algo`环境是模板`\newtheorem`出来的，并非由哪个宏包提供。

**Comment by YDX-2147483647** [comment]
根据`algorithm2e`宏包手册，在导言区加入这段命令即可。

```latex
\SetAlgorithmName{算法}{算法列表}
```

![图片](https://github.com/BITNP/BIThesis/assets/73375426/ed904d10-7d49-44d9-b38c-7e5488c99744)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/2de33f0c-fb9a-4001-af5d-ff0ded15d63c)

**Comment by fky2015** [comment]
可以，可以考虑结合 https://tex.stackexchange.com/questions/16199/test-if-a-package-or-package-option-is-loaded 实现

**Comment by RemnantCloude** [comment]
感谢，加入之后正常了
> 根据algorithm2e宏包手册，在导言区加入这段命令即可。
> ```\SetAlgorithmName{算法}{算法列表}```

另外我注意到使用**algorithm2e宏包**后默认的编号从**x.x**变成**x**，在宏包手册里找到了一个解决方法，仅供参考
```
\SetAlgoRefName{ref}
```
![image](https://github.com/BITNP/BIThesis/assets/40494051/c8b4c5a0-de64-45ac-90cd-31ef833d3f4b)

**Comment by RemnantCloude** [comment]
> 请问最后那个是什么意思？如果修改编号格式，我看应该引入宏包时加`algochapter`啊。

你说得对，抱歉，我对algorithm2e不是很熟悉，翻手册的时候也看漏了。我现在没有任何问题了
