### ISSUE TITLE
[硕士论文英语摘要报错]

### ISSUE THREAD

**Issue by Guozhenyuan** [BITNP/BIThesis#466]
### 发生了什么？

在使用硕士Latex模板时，英文摘要部分会报错，可能是包冲突引起，但是没有找到具体冲突点。

### 问题复现的步骤（或者截图）

编译报错

### 操作系统或平台

None

**Comment by Guozhenyuan** [comment]
![截屏2024-04-21 09 37 51](https://github.com/BITNP/BIThesis/assets/123309978/5a8e645b-5dd3-41b2-8bf0-b88027ad6aaa)
englishabstract改成abstractEn解决

**Comment by fky2015** [comment]
看起来你这个问题是在“旧模板迁移新模板时候”发生的。

是的，两个模板不兼容，所以需要用户基于我们的示例来“迁移内容“。
