### ISSUE TITLE
参考文献空白

### ISSUE THREAD

**Issue by kjn12** [BITNP/BIThesis#474]
### 发生了什么？

参考文献空白，正文中引用部分角标是bibtex中label的内容

### 问题复现的步骤（或者截图）

![屏幕截图 2024-04-22 213341](https://github.com/BITNP/BIThesis/assets/101028818/07fd5a05-3563-467c-ae0f-ef507a55531e)
![image](https://github.com/BITNP/BIThesis/assets/101028818/45c7ac2e-a7ab-4d69-889a-bbb8f966d245)

### 操作系统或平台

None

**Comment by YDX-2147483647** [comment]
是否试过清除缓存重新编译呢？

**Comment by fky2015** [comment]
一般是你的 LaTeX 有其他书写错误，导致参考文献的编译无法继续。

**Comment by kjn12** [comment]
操作系统是win11,编辑器是overleaf

**Comment by kjn12** [comment]
> 是否试过清除缓存重新编译呢？
> 
> 如果你介绍一下用的操作系统、编辑器、发行版（例如Windows、VS Code、TeX Live 2024），我可以帮你查查具体怎样清除缓存。
系统是win11,编辑器是overleaf

**Comment by YDX-2147483647** [comment]
看来大概率是书写错误了。重新编译那个大绿色按钮右边，应该有个日志按钮，这里写了什么？

**Comment by YDX-2147483647** [comment]
看来大概率是书写错误了。重新编译那个大绿色按钮右边，应该有个日志按钮，这里写了什么？

**Comment by kjn12** [comment]
> 看来大概率是书写错误了。重新编译那个大绿色按钮右边，应该有个日志按钮，这里写了什么？
有关参考文献的错误是这样的
![屏幕截图 2024-04-23 095231](https://github.com/BITNP/BIThesis/assets/101028818/07833e0d-8261-437b-a239-1db204fd2ef1)

**Comment by fky2015** [comment]
就这俩？建议截图的时候截取整个右侧。

**Comment by YDX-2147483647** [comment]
@kjn12 现在解决了吗？

**Comment by kjn12** [comment]
没有

**Comment by YDX-2147483647** [comment]
那发一下完整日志？
![图片](https://github.com/BITNP/BIThesis/assets/73375426/11202b35-c8dc-4e8f-8b8e-86670286c99d)

或者复制项目，换掉敏感信息，分享项目（可编辑/只读都行）？

![图片](https://github.com/BITNP/BIThesis/assets/73375426/9a7a31c4-6cc5-446d-8b45-1c17b60147d2)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/9f31d188-0634-4175-8944-75f5f98ccc7f)

**Comment by kjn12** [comment]
[output.log](https://github.com/BITNP/BIThesis/files/15088142/output.log)

**Comment by YDX-2147483647** [comment]
你之前成功编译过吗？成功过的话，还记得大概改了什么才这样吗？

日志的信息似乎还不够。能否编辑`main.tex`，把所有`\input{./chapters/*.tex}`注释掉，看是否正常？

- 若正常，逐一取消注释，看是哪章错了。
- 若不正常，检查导言区（`main.tex`开头`\usepackage`之类的）和`*.bib`。（检查不出来就也发一下文件）

**Comment by kjn12** [comment]
整个main.tex文档：
%%
% The BIThesis Template for Graduate Thesis
%
% Copyright 2020-2023 Yang Yating, BITNP
%
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either version 1.3
% of this license or (at your option) any later version.
% The latest version of this license is in
%   http://www.latex-project.org/lppl.txt
% and version 1.3 or later is part of all distributions of LaTeX
% version 2005/12/01 or later.
%
% This work has the LPPL maintenance status `maintained'.
%
% The Current Maintainer of this work is Feng Kaiyu.
%
% Compile with: xelatex -> biber -> xelatex -> xelatex

% !TeX program = xelatex
% !BIB program = biber

% 硕士论文模板 type=master
% 博士论文模板 type=doctor
% 开启盲审格式 blindPeerReview=true (如：[type=master,blindPeerReview=true])
% 开启双面打印模式 twoside=true (如：[type=master,twoside=true]）
%     在双面打印模式下，需要放在奇数页的页面后会自动插入一个空白页，以方便直接在打印机上“双面打印”。
%
% 在 Linux 和 macOS 系统下，由于版权问题，中文字体和 Windows 系统下的字体不同。
% 如果想要获得与 Word 文档相同的效果，你有两个选择：
% 1. 使用 Windows 系统编译最终的论文。
% 2. 自己手动安装中易字库并添加选项：`\documentclass[...,ctex={fontset=windows}]{bithesis}`。
%
% **更多使用说明请参考 bithesis.pdf **

\documentclass[type=master,twoside=false]{bithesis}

% 此处仅列出常用的配置。全部配置用法请见「bithesis.pdf」手册。
\BITSetup{
  cover = {
    %% 使用以下参数来自定义封面日期
    date = 2024年6月,
    autoWidthPadding = 0.25em,
  },
  info = {
    % 想要删除某项封面信息，直接删除该项即可。
    % 想要让某项封面信息留空（但是保留下划线），请传入空白符组成的字符串，如"{~}"。
    % 如需要换行，则用 “\\” 符号分割。
    classification = TQ028.1,
    UDC = 540,
    title = *****,
    % 如需覆盖竖排标题，请配置以下选项。
    % 下面的例子展示了如何在竖排标题中使用垂直或者旋转的英文。
    % verticalTitle = {形状记忆聚氨酯{L } {T } {X }的合成 \rotatebox[origin=c]{-90}{Feng Kaiyu} 及其在织物中的应用},
    titleEn = ****,
    author = ****,
    % 如果想要手动控制盲审模式下的隐藏信息，可以使用宏 \SecretInfo{}。使用方式有两种，如：
    % major = \SecretInfo{材料科学与工程} 可以得到 ******* （用等量的替换符号替代）
    % major = \SecretInfo{材料科学与工程}[ABCDEF] 可以得到 ABCDEF （用你自定义的内容替代）
    major = 信息与通信工程,
    school = 信息与电子学院,
    degree = 工学硕士,
    chairman = **教授,
    defenseDate = 2024年6月1日,
    supervisor = ****,
    authorEn = ***,
    schoolEn = Information and Electronics,
    supervisorEn = **** ,
    chairmanEn = Prof. **,
    degreeEn = Master of Engineering,
    majorEn = Information and communication Engineering, 
    defenseDateEn = {June, 12th, 2024},
    keywords = {****},
    keywordsEn = ***8
    % 必要时置于封面右上角，并按照国家规定进行标记。
    % classifiedLevel = 密级\BigStar 保密期限,
    %
    % 一下两个选项不勾选时将会隐藏显示。
    % 特别类型——交叉研究方向（一般不用勾选）
    % crossResearch = true,
    % 特别类型——政府项目留学生（一般不用勾选）
    % internationalStudentUGP = true,
  },
  % 在目录页中不显示摘要和主要符号对照表的标题。
  TOC = {
    abstract = false,
    abstractEn = false,
    symbols = false,
  },
  style = {
    pageVerticalAlign = top,
    % 开启 Windows 平台下的中易宋体伪粗体。
    % windowsSimSunFakeBold = true,
    % 开启该选项后，将用 Times New Roman 的开源字体 TeX Gyre Termes 作为正文字体。 
    % 这个选项适用于以下情况：
    % 1. 不想在系统中安装 Times New Roman。
    % 2. 在 Linux/macOS 下遇到 `\textsc` 无法正常显示的问题。
    % betterTimesNewRoman = true,
  },
  publications = {
    % 以下两个选项将影响「攻读学位期间发表论文与研究成果清单」中名称列表的省略阈值。
    % 一般来说，如果你在全部文献中最低排在第四位，建议你将两个值都设置为 4。
    % 更详细的说明请见手册。
    maxbibnames = 3,
    minbibnames = 1,
  },
  % 采用章节标题级别的附录格式
  appendices / chapterLevel = true,
  const = {
    % 由于现存的 Word 模板、旧有 LaTeX 模板与《北京理工大学研究生学位论文撰写规范》的规定不一致，
    % 论文封面的某些字段内容需要用户根据自己的情况进行手动调整。
    % 目前给出的默认值是按照 2018 年发布的《北京理工大学研究生学位论文撰写规范》中的要求进行设置的。
    % 比如注释掉的这一行：将会修改封面中的「申请学位级别」为「申请学位」。
    % info / degree = {申\quad{}请\quad{}学\quad{}位},
    % info / major = {学\quad{}科\hspace{5pt}/\hspace{5pt}类\quad{}别}
  },
  misc = {
    % 关闭后，链接会用多种颜色表示，便于检查。
    % 无论是否开启，都不会影响打印效果。
    hideLinks = true,
  }
}

% 大部分关于参考文献样式的修改，都可以通过此处的选项进行配置。
% 详情请搜索「biblatex-gb7714-2015 文档」进行阅读。
\usepackage[
  defernumbers=true,
  backend=biber,
  style=gb7714-2015,
  gbalign=gb7714-2015,
  gbnamefmt=lowercase,
  gbpub=false,
  gbannote=true,
  gbpunctin=false,
  doi=false,
  url=false,
  eprint=false,
  isbn=false,
]{biblatex}

% 添加参考文献
\addbibresource{reference/main.bib}
% 攻读学位期间发表论文与研究成果清单，详细使用方法见 `chapters/pub.tex`。
%\addbibresource{reference/pub.bib}


\usepackage{graphicx}

\begin{document}

% 封面绘制
\MakeCover

% 打印书脊
\MakePaperBack

% 中文信息与英文信息
\MakeTitle

% 论文原创性声明和使用授权
\MakeOriginality

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 前置部分
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frontmatter

% 摘要
\input{./chapters/abstract.tex}

% 制作目录
\MakeTOC

% 插图目录
\listoffigures
% 表格目录
\listoftables

% 主要符号对照表
\input{./misc/0_symbols.tex}

\mainmatter

% 请根据论文内容，按照顺序添加章节。
\input{./chapters/chap1.tex}
\input{./chapters/chap2.tex}
\input{./chapters/chap3.tex}
\input{./chapters/chap4.tex}

\backmatter

% 结论
\input{./misc/1_conclusion.tex}
% 参考文献
\input{./misc/2_reference.tex}

% 附录
\input{./misc/3_appendices.tex}

% 个人成果
%\input{./misc/4_pub.tex}

% 致谢
\input{./misc/5_acknowledgements.tex}
% 个人简介（仅博士生需要此项）
\input{./misc/6_resume.tex}

% 加入目录
\end{document}


之前我使用的是旧模板，后来用新模板把所有章节的bib文件内容粘贴到main,bib后就没有成功过

**Comment by fky2015** [comment]
旧模板不建议这么简单粗暴的迁移。建议一点一点添加，保证每次的改动都是成功的。

**Comment by fky2015** [comment]
由于没有更多信息提供，因此关闭此 Issue。
