### ISSUE TITLE
Release CI 从 v3.7.1 开始未能更新`CHANGELOG.md`

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#478]
https://github.com/BITNP/BIThesis/actions/workflows/release.yml 从 v3.7.1 开始未能更新`CHANGELOG.md`，因为`main`分支有保护，生成后不让直接提交。

https://github.com/BITNP/BIThesis/blob/3fd7b2269e8840737d4f82fd1e3a981104b584dc/CHANGELOG.md?plain=1#L17

![图片](https://github.com/BITNP/BIThesis/assets/73375426/e8e55f5e-7eec-4a1e-a3b4-a306ccebfead)

```log
Run git config user.name 'github-actions[bot]'
  git config user.name 'github-actions[bot]'
  git config user.email 'github-actions[bot]@users.noreply.github.com'
  set +e
  git add CHANGELOG.md
  git commit -m "Update changelog"
  git push https://***@github.com/BITNP/BIThesis.git main
  shell: /usr/bin/bash -e {0}
[main a632684] Update changelog
 1 file changed, 743 insertions(+), 839 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through the merge queue        
To https://github.com/BITNP/BIThesis.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/BITNP/BIThesis.git'
```

## 历史

1. v3.7.1 / https://github.com/BITNP/BIThesis/commit/54bbe79e3dbcb22d2f94ae2123a4ba255ff2c2e5 删除了一个job。
2. v3.7.2 / https://github.com/BITNP/BIThesis/commit/53e9cee04d8d4a977fb0936709868e4e31ec3828 加了 Update changelog，但后来只有一次在`cliff-update`分支成功运行，其它在`main`分支都被拦住了。

**Comment by fky2015** [comment]
是的，我暂时没想好怎么处理

**Comment by fky2015** [comment]
可以，不过请搭配 auto-merge 一起使用。

**Comment by fky2015** [comment]
那我们是不是可以发个新版本试验一下？

**Comment by YDX-2147483647** [comment]
好，你操作？

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/commit/64479bb5d8dc83561357f66940c132d168a3a242 牛牛牛！
