### ISSUE TITLE
本科全英文模板

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#496]
首先，目前本科全英文有对应的官方Word模板吗？

其次，群里同学提出了[北京理工大学管理与经济学院本科生毕业设计（论文）模板（英文论文）.docx](https://github.com/BITNP/BIThesis/files/15270365/default.docx)。

> 1. ✅标题页面和中文版类似，但是英文标题在上，中文在下；
> 2. ❌原创声明是中文版的；
> 3. ✅英文abstract在中文摘要前；
> 4. ✅前几页的序号是大写罗马数字I II II；
> 5. ✅页眉是中文版的；
> 6. ✅后面的格式同英文版。

除此以外，✅Word中标题是衬线体Times New Roman，而BIThesis是无衬线体；✅单复数也不同。

![4F4RZ`A3F~1DSP)Y FP5DEO](https://github.com/BITNP/BIThesis/assets/73375426/ca7c98ac-356f-4189-a625-2562cfce2670)
↑以上“管理与经济学院本科生毕业设计（论文）模板（英文论文）”

↓现有模板
![%T$I13C0 OE1@TEX}14YHH](https://github.com/BITNP/BIThesis/assets/73375426/2c3dec63-2c42-4f51-b33b-622519210368)

✅2024年5月17日补充：英文模板目前目录含目录，并且其页码有同学反映是目录最后一页，而非第一页，可能有问题。（中文模板的目录不含目录。）

**Comment by fky2015** [comment]
[本科-全英文 Thesis Format 2022.pdf](https://github.com/BITNP/BIThesis/files/15274472/-.Thesis.Format.2022.pdf)
[本科-全英文 Thesis Sample 2021 with signature.pdf](https://github.com/BITNP/BIThesis/files/15274475/-.Thesis.Sample.2021.with.signature.pdf)

我手头也是之前有人给我的，不是官方的。

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis/blob/959fb1c75a0dc3edc974ad8c47004bfc8698399f/templates/undergraduate-thesis-en/main.tex#L43-L49

> 全英文模板建议这里加一个title，会在摘要中出现

另外Bachelor拼错了。

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis/blob/959fb1c75a0dc3edc974ad8c47004bfc8698399f/templates/undergraduate-thesis-en/main.tex#L43-L49

> 全英文模板建议这里加一个title，会在摘要中出现

另外Bachelor拼错了。

**Comment by YDX-2147483647** [comment]
## 调查

- 信息学院

  用现有 LaTeX 英文模板 + 中文模板的封面可以通过（同学反馈希望能自选封面中文还是英文）；页眉要求用中文，但用英文也没大问题；双语原创性声明并没规定模板。

  信息学院没有全英文班，英文论文较少。这可能导致格式比较松。

另：[在招本科专业设置及培养方案 - 教务部](https://jwb.bit.edu.cn/dlpy/zysz/a45637815a954503b86ec12c74b840e2.htm)可查看哪些学院有全英文班。

**Comment by YDX-2147483647** [comment]
# 目录页码错误问题

目前英文模板的目录里有目录。


5月17日有人反馈目录的页码是目录最后一页，而非第一页。

原因在于


#480
#522
