### ISSUE TITLE
[Bug]: 附录引用问题

### ISSUE THREAD

**Issue by Devil-SX** [BITNP/BIThesis#502]
### 发生了什么？

如果在附录里引用了前文未引用的文章，则无法在 reference 里显示出来该文章。

### 问题复现的步骤（或者截图）

1. 在 bib 里添加文章
2. 在 appendix 里引用文章
3. 查看渲染的 reference

### 操作系统或平台

None

**Comment by YDX-2147483647** [comment]
诶？自己解决了？

**Comment by Devil-SX** [comment]
> 诶？自己解决了？

误报 bug 233
