### ISSUE TITLE
[Bug]: 硕博模板书脊不适应长标题

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#505]
### 发生了什么？

标题很长时，书脊的标题、姓名、学校会粘在一起。即使下面有空，也不往下挪。

![IRYFQKT9E{}6E6_$W30 _33](https://github.com/BITNP/BIThesis/assets/73375426/a65bbb33-a012-4006-9b46-c8aa923f0f21)

### 你期望的结果

![VXP$AU{{OJE9V`NJ3}7@ )I](https://github.com/BITNP/BIThesis/assets/73375426/0c7cc685-1f99-41f5-ba74-75c86da51c3e)

### 问题复现的步骤（或者截图）

足够长的标题：八月秋高风怒号卷我屋上三重茅茅飞渡江洒江郊高者挂罥长林梢下者飘转沉塘坳

### 相关代码

这俩`\vfill`有时无效，原因不明。

https://github.com/BITNP/BIThesis/blob/2f6cf63d054e67bc7a07948a02d2f03f5521a075/bithesis.dtx#L1929-L1931

**Comment by YDX-2147483647** [comment]
### 临时解决方案

编辑`bithesis.cls`，搜索“书脊”，把上面提到的两处`\vfill`换成`\vspace{1em}`。

**Comment by YDX-2147483647** [comment]
给书脊的`minipage`环境套`\fbox{…}`，发现框太小了。

![图片](https://github.com/BITNP/BIThesis/assets/73375426/a22574ea-6906-452c-904c-4238de2621ad)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/82b129b1-e21b-4c02-9d88-c0921695778f)

**Comment by fky2015** [comment]
> 距下边界均为 5cm 左右。

当时编写时参考的要求。

**Comment by YDX-2147483647** [comment]
那上边距有要求吗？

![图片](https://github.com/BITNP/BIThesis/assets/73375426/ecca02dd-d36d-43ac-9bfd-d334022f3f1f)

**Comment by YDX-2147483647** [comment]
```latex
% 对齐中西基线
% https://tex.stackexchange.com/a/38585
\newcommand*\CJKmovesymbol[1]{\raise.35em\hbox{#1}}
\newcommand*\CJKmove{\punctstyle{plain}% do not modify the spacing between punctuations
  \let\CJKsymbol\CJKmovesymbol
  \let\CJKpunctsymbol\CJKsymbol}
% \begin{macro}{\make_paper_back:}
% 制作书脊。
%    \begin{macrocode}
\cs_new:Npn \make_paper_back: {
  \cleardoublepage
  \currentpdfbookmark{书脊}{frontmatter:paperback}
  \begin{titlepage}
    % 上下各留出规定的边距，到下一页再恢复
    \newgeometry{
      vmargin = 5cm,
    }
    \centering
    % 把盒子竖过来，盒子内相当于一行；再把汉字利用字体特性转回来。
    % 存在的问题：破折号断开
    \rotatebox[origin=lt]{-90}{
      % 实际使用时：\framebox → \makebox
      \framebox[\textheight]{
        \heiti\zihao{3}
        \addCJKfontfeatures*{RawFeature={vertical}}
        \CJKmove
        %
        % 标准例子：
        形状记忆聚氨酯的合成及其在织物中的应用
        %
        % 西文例子：
        % 形状记忆聚氨酯 \hspace{0.2em}
        % \rotatebox{90}{L} \hspace{0.2em}
        % \rotatebox{90}{T} \hspace{0.2em}
        % \rotatebox{90}{X} \hspace{0.2em}
        % 的合成Feng Kaiyu及其在织物中的应用
        %
        % 超长例子：
        % 八月秋高风怒号卷我屋上三重茅茅飞渡江洒江郊高者挂罥长林梢下者飘转沉塘坳
        \hspace{1em plus 1fill}
        杜甫
        \hspace{1em plus 1fill}
        北京理工大学
      }
    }
    \restoregeometry
  \end{titlepage}
}
```

![图片](https://github.com/BITNP/BIThesis/assets/73375426/ae056572-bb74-4cc3-871b-c8cc0443d1c4)
![图片](https://github.com/BITNP/BIThesis/assets/73375426/5e3476b7-e634-42fc-b9ea-bb973ce4519e)

![图片](https://github.com/BITNP/BIThesis/assets/73375426/1d96fe3f-f207-422c-a65b-6fd04d2bc6e6)

**Comment by YDX-2147483647** [comment]
## 测量像素结果

- Word模板：上 57 mm，下 46 mm。（两个Word模板一样）
- LaTeX v3.7.7 模板：上 37 mm，下 60 mm。

**Comment by YDX-2147483647** [comment]
冷知识：[现在](https://github.com/BITNP/BIThesis/releases/tag/v3.8.3-alpha-1)可以写 2×5×4 = 40 个汉字。

```
关关雎鸠口在河之洲口窈窕淑女口君子好逑口参差荇菜口左右流之口窈窕淑女口寤寐求之口
```

![Image](https://github.com/user-attachments/assets/4c188bee-ec2e-41db-95ab-b749d7c53dae)

（刚才有人用旧版遇到相同问题）
