### ISSUE TITLE
教程

### ISSUE THREAD

**Issue by AemonSnow** [BITNP/BIThesis#512]
### 发生了什么？

模版提供的教程对于初学者来说仍然不够清楚。

### 你期望的结果

我试着写了一个简单的教程，不知道可不可以提交

**Comment by YDX-2147483647** [comment]
> 模版提供的教程

网站似乎没有教程，只有[📃 LaTeX 学习与使用资源 | BIThesis](https://bithesis.bitnp.net/guide/resources.html) 这些链接；另外有个快速使用手册（ https://github.com/BITNP/BIThesis/tree/0bffec67a3d774fcd19e14b19d0b32f0c75009b0/the-graduates-handbook ），目前PDF只发给了教务部，GitHub Releases 还没发过。

之所以自己不提供教程，可能是考虑到维护成本？（→ [我应该选择 LaTeX 还是 Word？](https://blog.fkynjyq.com/should-i-choose-between-bithesis-or-word) - [前言 | BIThesis](https://bithesis.bitnp.net/guide/preface.html#q-%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E6%8B%A9-latex-%E8%BF%98%E6%98%AF-word)）

> 我试着写了一个简单的教程，不知道可不可以提交

- 形式：PDF文件还是markdown网页呢？
- 发布方式：如果添加，想放到哪里？

**Comment by AemonSnow** [comment]
我阅读过这些教程，感觉对于latex的初学者还是不太适合。作为一个软工学生看完都有些茫然，更别说那些非计算机相关专业的人了。
对于在开始撰写论文时才开始使用Latex模版的人来说，目前的使用手册的内容并不能解决最基础的问题：我怎么才能用这个写论文？
我自己写了个md文件的教程，因为这样感觉比较方便维护。至于发布到哪里，感觉可以放到每个模版的文件夹里方便查阅，或者在网站上加一个“快速开始”的页面。

**Comment by AemonSnow** [comment]
> 网站似乎没有教程

我阅读过这些教程，感觉对于latex的初学者还是不太适合。作为一个软工学生看完都有些茫然，更别说那些非计算机相关专业的人了。
对于在开始撰写论文时才开始使用Latex模版的人来说，目前的使用手册的内容并不能解决最基础的问题：我怎么才能用这个写论文？

> * 形式：PDF文件还是markdown网页呢？
> * 发布方式：如果添加，想放到哪里？

我自己写了个md文件的教程，因为这样感觉比较方便维护。至于发布到哪里，感觉可以放到每个模版的文件夹里方便查阅，或者在网站上加一个“快速开始”的页面。

**Comment by YDX-2147483647** [comment]
好；还有个问题：你目前写的教程是针对BIThesis模板（接近快速使用手册§1–§3），还是适用于一般LaTeX（接近§4）呢？

本科快速使用手册：[undergraduate-handbook.pdf](https://github.com/BITNP/BIThesis/files/15416316/undergraduate-handbook.pdf)

**Comment by AemonSnow** [comment]
> 好；还有个问题：你目前写的教程是针对BIThesis模板（接近快速使用手册§1–§3），还是适用于一般LaTeX（接近§4）呢？
> 
> 本科快速使用手册：[undergraduate-handbook.pdf](https://github.com/BITNP/BIThesis/files/15416316/undergraduate-handbook.pdf)


针对BIThesis模版。不过我刚刚读了一下快速使用手册发现其实挺好的。。。。但是我不知道为什么没看过。抱歉浪费您的时间，不过我建议您把这个文件放进模版文件夹并换个更直接的中文文件名

**Comment by YDX-2147483647** [comment]
👉 #516

不过没放模版文件夹里，因为快速使用指南还介绍了如何下载模板，下载后再看有点儿怪……
