### ISSUE TITLE
[Bug]:  本科论文模板参考文献在会议名前多出两条斜杠

### ISSUE THREAD

**Issue by dukmu** [BITNP/BIThesis#525]
### 发生了什么？

添加参考文献，在正文中引用，编译结果如下：
![image](https://github.com/BITNP/BIThesis/assets/74289192/9e3b7faa-89f4-4f6c-a53e-e675611c6572)

### 你期望的结果

按照参考文献格式要求，没有双斜杠

建议在模板里注明如何去除双斜杠。

### 操作系统或平台

Windows

### LaTeX 发行版以及发行年份

latest

### BIThesis 模板

undergraduate-thesis

**Comment by YDX-2147483647** [comment]
这是GB/T 7714—2015对析出文献（从会议论文集里“析出”一篇，只引用这一篇）的要求。

如果你确实想改，请参考 https://github.com/BITNP/BIThesis/discussions/477 。

P.S. 毕业设计《书写规范及打印装订要求》和模板的“参考文献”一节都介绍了参考文献书写规范，且都声称参考 GB/T 7714—2015《信息与文献　参考文献著录规则》。然而这三个文件两两不一致……今年1月我专门问过信息学院的教学干事，回复说以GB/T 7714—2015为准。

**Comment by fky2015** [comment]
> 按照参考文献格式要求，没有双斜杠

可以理解为参考文献只给出了一种可能（甚至是错误的）。和教务部的老师也确认过，可以使用带有双斜杠的格式（完全符合国标）。如果不是盲评在 B 以下，被要求一定要修改的话（有些老师比较固执），可以忽略这个问题。

**Comment by dukmu** [comment]
明白了
