### ISSUE TITLE
手册中关于 Overleaf 的使用方式应该更新

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#532]
已经引入了更简便的方式，不再需要手动 Clone 项目。

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis/pull/530/files#diff-2ce2e051aa4dc42ff73d57eff133916b4dcd224960fbddc5c0c3c51a9b1dd216
已经改了？

**Comment by fky2015** [comment]
my bad
