### ISSUE TITLE
快速使用指南没有介绍盲评事项

### ISSUE THREAD

**Issue by YDX-2147483647** [BITNP/BIThesis#533]
在本科方面，似乎只有`main.tex`中有注释介绍，引发不少困惑。

有同学自己改了`\BITSetup`别的选项：

> 老师，依照通知的意思，使用word文档的同学，“略去”是删去吗？我们有使用latex的同学，他的latex里面设置成盲审版是保留封面，但是个人信息全变成了星号

有同学自己改，结果差了原创性声明：

> 直接把makecover注掉也行
> 致谢在后置部分，也可以注掉，不会出bug

**Comment by YDX-2147483647** [comment]
https://github.com/BITNP/BIThesis/blob/2f6cf63d054e67bc7a07948a02d2f03f5521a075/templates/undergraduate-thesis/main.tex#L39-L40

也许可以直接修改本科这个选项的默认值，避免在`main.tex`中设置？

**Comment by fky2015** [comment]
我大致明白你的意思了，你想要取消这个参数，改为通过模板类型来判断封面信息隐藏类型。
唯一的担心是，如果某个同学坚持需要另一种样式，那么新的模板将无法做到。（确实不太可能发生）。

我比较赞同这个方式。（同时需要考虑兼容性，不能直接删除这个参数）
