### ISSUE TITLE
请问如何编辑每一章最后的成果部分

### ISSUE THREAD

**Issue by tangyj2008ok** [BITNP/BIThesis#560]
### 发生了什么？

已经完成了章节撰写，需要在 “本章小结” 后面换一种字体说明本章的论文，这部分请问应该如何添加？

### 操作系统或平台

Overleaf

**Comment by fky2015** [comment]
> 需要在 “本章小结” 后面换一种字体说明本章的论文

可否提供一个具体示例？

**Comment by fky2015** [comment]
https://github.com/BITNP/BIThesis/discussions/435 看看这个是不是你想要的？

**Comment by YDX-2147483647** [comment]
是否还有问题？如果没有，可以关闭这个 issue。
