### ISSUE TITLE
移除对 sourcerer.io 的依赖

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#67]
1. [sourcerer.io](https://sourcerer.io/) 的证书已经过期。

![image](https://user-images.githubusercontent.com/16451516/104115354-83917c80-5349-11eb-9d4d-8c2357b08540.png)

2. [项目整体维护读也不高](https://github.com/sourcerer-io)。

3. 这个模块与 Github 去年上线的 Contributer 功能重复了。
4. 在 Readme 中手动更新这个部分很麻烦。

因此，计划移除这部分内容。

**Comment by spencerwooo** [comment]
:+1:

**Comment by spencerwooo** [comment]
Sourcerer 原来被收购了啊，看：https://github.com/sourcerer-io/sourcerer-app/issues/632
