### ISSUE TITLE
更新 wiki 中适配 2.0 部分的文档 

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#68]
1. 查看视频中2.0版本需要更改的地方
2. 查看文档中2.0版本需要更改的地方

**Comment by guguguxiao** [comment]
- 视频
  -  《2.latex的下载和安装》添加更新到最新版本texlive并检测bithesis成功安装的教程
  -  《4.模板的下载和使用》 2：48 ，3：05，4：00处出现的代码行数错误
  -  《1.教程介绍》《5.格式转换》结尾处以及《4.模板的下载和使用》0：26处github地址改为最新地址 
- 文档
  - 下载合适的 LaTeX 发行版部分   教程中使用texlive2019，需要更新到最新版本并检测bithesis宏包是否成功安装
  - bithesis模板部分   关于代码出现行数的部分全要更正，并且超链接失效
