### ISSUE TITLE
更新视频教程到新版

### ISSUE THREAD

**Issue by fky2015** [BITNP/BIThesis#72]
- [x] 分析视频方面有哪些地方必须做出改动
- [ ] 写一个简单的方案
- [ ] 联系相关人员进行修改
- [ ] 更新链接资源

**Comment by ZIJIN-Evan** [comment]
修改方案是否有进展？

**Comment by fky2015** [comment]
简单方案见：
https://github.com/BITNP/BIThesis/issues/68#issuecomment-768866839

目前主要考虑到 V1 与 V2 版本间的变更其实不是很大；再加之不知道视频修改需要涉及多少工作量，因此没有给这个事情高优先级。
