### ISSUE TITLE
latex 编译 报错 "bitbook.cls not found"

### ISSUE THREAD

**Issue by lostsword** [BITNP/BIThesis#74]
你好，使用的是release中的2.0版本
报错信息：
`File bitbook.cls' not found. `
编译环境：
`pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02`

是否是需要源代码重新make 生成cls文件

**Comment by lostsword** [comment]
是对2.0.0版本中`graduation-thesis/main.tex`编译

**Comment by fky2015** [comment]
可以参考 [🍌 如何开始 | BIThesis](https://bithesis.bitnp.net/Guide/1-Intro/First-things-first.html#%E6%9B%B4%E6%96%B0-latex-%E7%8E%AF%E5%A2%83%E8%87%B3%E6%9C%80%E6%96%B0) 更新 LaTeX 环境至最新，或者手动安装 bithesis 宏集。

**Comment by lostsword** [comment]
> 可以参考 [🍌 如何开始 | BIThesis](https://bithesis.bitnp.net/Guide/1-Intro/First-things-first.html#%E6%9B%B4%E6%96%B0-latex-%E7%8E%AF%E5%A2%83%E8%87%B3%E6%9C%80%E6%96%B0) 更新 LaTeX 环境至最新，或者手动安装 bithesis 宏集。

因为更新latex比较麻烦，但手动安装bithesis 宏集时会报错
我使用以下命令，安装bithesis 宏集
`tlmgr update --self --all`
报错信息如下：
`tlmgr.pl: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.`

**Comment by fky2015** [comment]
请问你是用的是 Windows 么？

**Comment by lostsword** [comment]
> 请问你是用的是 Windows 么？

是的

**Comment by fky2015** [comment]
Windows 环境建议直接安装 2021 的 Tex Live 环境。因为手动升级比较麻烦。

**Comment by lostsword** [comment]
好的，非常感谢
