### ISSUE TITLE
Windows系统Tex Live安装失败问题

### ISSUE THREAD

**Issue by guozhihanguozhihan** [BITNP/BIThesis#76]
管理员身份运行exe文件

**Comment by Lancern** [comment]
请提供更加具体的问题描述，包括操作系统版本、复现错误所需的所有操作步骤、任何可能的错误消息、错误截图等。

**Comment by fky2015** [comment]
> 请提供更加具体的问题描述，包括操作系统版本、复现错误所需的所有操作步骤、任何可能的错误消息、错误截图等。

@Lancern  我的我的，大致问题是她发现在 Windows 安装 Tex Live 时，如果不使用管理员权限会导致非预期的安装结果。我让她提个 Issues，我们好补充一下文档。
