### ISSUE TITLE
页面底部文字离页码很近

### ISSUE THREAD

**Issue by grandN2H4** [BITNP/BIThesis#77]
有些页面（比如说整页都是字）会出现底部文字离页码很近的情况，请问如何解决呢？我想放个图说明一下的，但是这里好像放不了哎

**Comment by fky2015** [comment]
可以放哒，直接粘贴图片就可以。
如果因为网络原因实在无法放图片的话，可否提供一个最小的可复现示例？
或者移步我们的 Slack 社区以上传图片。

**Comment by grandN2H4** [comment]
[图片]

**Comment by grandN2H4** [comment]
> 可以放哒，直接粘贴图片就可以。
> 如果因为网络原因实在无法放图片的话，可否提供一个最小的可复现示例？
> 或者移步我们的 Slack 社区以上传图片。

好哒，我去Slack上放了图，有时间的话麻烦帮忙看看哦~蟹蟹~

**Comment by grandN2H4** [comment]
> 可以放哒，直接粘贴图片就可以。
> 如果因为网络原因实在无法放图片的话，可否提供一个最小的可复现示例？
> 或者移步我们的 Slack 社区以上传图片。
好哒，我去Slack上放了图，有时间的话麻烦帮忙看看哦~蟹蟹~

**Comment by fky2015** [comment]
能够复现该问题，作为临时解决方案，可以在 `main.tex` 文档开始（30 行）之前添加一下语句:

```LaTeX
\fancypagestyle{BIThesis}{
  \setlength{\footskip}{26pt}
}
```
可以通过调整 `26pt` 这个值来调整页眉高度。

**Comment by ephemer1s** [comment]
> 能够复现该问题，作为临时解决方案，可以在 `main.tex` 文档开始（30 行）之前添加一下语句:
> 
> ```
> \fancypagestyle{BIThesis}{
>   \setlength{\footskip}{26pt}
> }
> ```
> 
> 可以通过调整 `26pt` 这个值来调整页眉高度。

这个方法不行啊 页眉会乱掉

**Comment by grandN2H4** [comment]
> > 能够复现该问题，作为临时解决方案，可以在 `main.tex` 文档开始（30 行）之前添加一下语句:
> > ```
> > \fancypagestyle{BIThesis}{
> >   \setlength{\footskip}{26pt}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以通过调整 `26pt` 这个值来调整页眉高度。
> 
> 这个方法不行啊 页眉会乱掉

可以在bitbook.cls中找到这个参数，进行更改
