### ISSUE TITLE
参考文献及条目类段落格式与word模板不符

### ISSUE THREAD

**Issue by ephemer1s** [BITNP/BIThesis#79]
Hi there. 我是自动化学院某头铁的本科生，正在使用BITThesis模板进行毕业论文撰写。
在盲评意见稿中，reviewer给出了一些令人迷惑不知道如何修改的格式意见，其中有这样两个问题

### 格式问题：

- 文中多处**1、2、3、4、这种条目类段落**格式应仍然按照正文格式，**行间距22磅，段前段后没有间距，首行缩进2个字符，其他无缩进**
- 文献格式不对，仔细按照模板进行修改
例如：
会议论文集
[序号]析出责任者. 析出题名[A]. **见(英文用In)**: 主编. 论文集名[C]. (供选择项: 会议名, 会址, 开会年)出版地: 出版者, 出版年. 起止页码. 
[5] 孙品一. 高校学报编辑工作现代化特征[A]. 见: 张为民编. 中国高等学校自然科学学报研究会. 科技编辑学论文集(2)[C]. 北京: 北京师范大学出版社, 1998. 10-22. 

图为我目前的情况：
### 问题1
![image](https://user-images.githubusercontent.com/62980323/120281013-057b4580-c2eb-11eb-97a3-9fcfe4697bd3.png)
### 问题2
![image](https://user-images.githubusercontent.com/62980323/120281219-407d7900-c2eb-11eb-9cb3-ac2d8815d266.png)

- 重新看了一下，盲审意见应该是**enumerate环境的段前后间距应为0，且应无悬挂缩进只有首行缩进**。

# 希望大佬们提出宝贵的建议与帮助！已一键三连！

**Comment by ephemer1s** [comment]
补充一下，参考文献是用的bibtex，整个项目是在overleaf环境下编译的

**Comment by fky2015** [comment]
### 关于文献格式问题

可以参考 https://github.com/BITNP/BIThesis/issues/66 。简单来说，原有模板采用的是曾经的国标，我们采用的是国标；并且已经和教务处、图书馆的老师确认过我们的格式符合国标。

> 已经的到官方的确认，我们遵守国标即可。

### enumerate 环境缩进问题

只需搜索 `LaTeX enumerate no indent` 等关键字即可找到相关答案，比如[这个回答提供了取消 enumerate 缩进的方式](https://tex.stackexchange.com/a/241988)：

```latex
\begin{enumerate}[leftmargin=*]
\item first item here
\item second item here
\item third item and so on ...
\end{enumerate}
```

**Comment by fky2015** [comment]
关于文献格式的问题，如果影响不大的话，我建议跟你的指导老师进行一下沟通，说明情况。目前我们这边比较难以在这么短时间内解决这个有关依赖第三方库的问题。

**Comment by hushidong** [comment]
参考文献可以见如下例子：

```

%

\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage[backend=biber,style=gb7714-2015,gbpunctin=false]{biblatex}
\usepackage{geometry}

\DefineBibliographyStrings{english}{
    in={In: }
}

\DeclareStyleSourcemap{
    \maps[datatype=bibtex]{
        \map[overwrite]{
            \pertype{inproceedings}
            \pertype{conference}%兼容老的conference类型
            \step[fieldset=usera, fieldvalue={A}]
            }
    }
}

\DeclareFieldFormat{booktitlecase}{\MakeCapital{#1}\nobreak[C]}

\renewbibmacro*{booktitle}{%
  \ifboolexpr{
    test {\iffieldundef{booktitle}}
    and
    test {\iffieldundef{booksubtitle}}
  }
    {}
    {\printtext[booktitle]{\bibtitlefont%
       \printfield[booktitlecase]{booktitle}%
       \setunit{\subtitlepunct}%
       \printfield[titlecase]{booksubtitle}}%
     \setunit{\subtitlepunct}}%
  \printfield{booktitleaddon}}




\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}

@Inproceedings{r27-BenHadjAlaya-FekiA.2008-1-5,
  Title                    = {Interference cartography for hierarchical dynamic spectrum access},
  Address                  = {Chicago, IL},
  Author                   = {{Ben Hadj Alaya-Feki A.} and B. Sayrac and S. Ben Jemaa and E. Moulines},
  Booktitle                = {Proc. IEEE Symp. on New Frontiers in Dynamic Spectrum Access Networks (DySPAN)},
  Date                     = {2008-10},
  Pages                    = {1-5}
}

@InProceedings{王临慧2010-138,
  author    = {王临慧},
  title     = {从几组声母的演变看天津方言形成的自然条件和历史条件},
  bookauthor= {曹志耘},
  booktitle = {汉语方言的地理语言学研究：首届中国地理语言学国际学术研讨会论文集},
  year      = {2010},
  publisher = {北京语言大学出版社},
  pages     = {138},
  address   = {北京},
}

\end{filecontents}

\addbibresource{\jobname.bib}
%\addbibresource{example.bib}

\begin{document}

\cite{王临慧2010-138,r27-BenHadjAlaya-FekiA.2008-1-5}


\printbibliography


\end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/120602638-cdf0d280-c47d-11eb-84ea-f1bac830ae8e.png)

**Comment by ephemer1s** [comment]
已解决，十分感谢！
