### ISSUE TITLE
校外指导教师插入的问题

### ISSUE THREAD

**Issue by Piamen** [BITNP/BIThesis#80]
加入校外指导教师之后，日期一行被挤到第二页了，是不是只能手动调整距离呢？
![校外指导教师](https://user-images.githubusercontent.com/35070253/120583526-fae2bc80-c460-11eb-8375-0471f3712927.png)

**Comment by fky2015** [comment]
是的。临时的解决请修改 `misc/0_cover.tex` 。后续我们会修复这个问题。
