### ISSUE TITLE
[bug]模板正文逗号生成的是占一整格汉字字符宽度的半角的逗号

### ISSUE THREAD

**Issue by ephemer1s** [BITNP/BIThesis#83]
![image](https://user-images.githubusercontent.com/62980323/121160142-67552580-c87e-11eb-9342-a5ac4e7872ab.png)
latex模板正文逗号生成的是半角的逗号，虽然占一整格汉字字符。

**Comment by fky2015** [comment]
不是的。

简单的检查方式：在 pdf 中选中相应的逗号，复制到其他地方。你会发现是全角逗号。

**Comment by ephemer1s** [comment]
他确实是全角逗号，但是编译出来是英文半角逗号的外观，通不过学院检查
已经解决了，是字体库的问题。

上传一个新的simsun.ttf并且设置`\setCJKmainfont{simsun.ttf}`就可以了
