### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by 2learnsomething** [BITNP/BIThesis#89]
作者您好，在压缩包paper-translation当中，我编译时发现缺少bitbook.cls文件，能否麻烦您上传一下呢？

**Comment by fky2015** [comment]
Fixed in https://github.com/BITNP/BIThesis-scaffold/commit/d000fb5583abcb90144e061fc545ea50cac1d1d1 .

任何遇到此问题的用户请使用最新的模板。
