### ISSUE TITLE
是否适用2022年的毕业设计

### ISSUE THREAD

**Issue by 2learnsomething** [BITNP/BIThesis#91]
我查看了一下学校的word模板，感觉好像有点差异，所以想确认一下这个模板是否和2022年的毕业设计的要求相一致，能够满足2022年的毕业设计要求。在此附上链接页面下方有附件，请学长查看，谢谢您! https://jwc.bit.edu.cn/sjjx/bysj/e06605ca60ec480d80bd6497560f70f7.htm

**Comment by fky2015** [comment]
我下周会开始处理这个问题。

**Comment by fky2015** [comment]
2022 的毕设模板采用的是 2020 年 4 月的模板。因此显然，2022 年的模板相较于 2021 年的模板并无改动。
![image](https://user-images.githubusercontent.com/16451516/147740503-a33e90ed-6eb5-4903-8d2a-639fe2449b1c.png)

如果你觉得哪里有差异，请具体指出问题。
