### ISSUE TITLE
专业名过长时，排版错误

### ISSUE THREAD

**Issue by everything411** [BITNP/BIThesis#92]
![image](https://user-images.githubusercontent.com/32010059/147317220-5cb56576-4a27-4e9d-96b9-2450f6439370.png)

**Comment by phy25** [comment]
比较好奇，期望的效果是折行还是挤压呢？

**Comment by everything411** [comment]
> 比较好奇，期望的效果是折行还是挤压呢？

在word里面敲了一下两种方案
1.

![image](https://user-images.githubusercontent.com/32010059/147376566-390c1eac-3b83-459a-adce-3ebdea0bfc59.png)

2.

![image](https://user-images.githubusercontent.com/32010059/147376571-6b3b30da-c349-4c91-afb4-11e9042d1d53.png)

似乎折行更加美观

**Comment by fky2015** [comment]
目前感觉只能手动修改 `misc/cover.tex` 以达到想要的换行效果。

究其原因是因为，每个行之间是手动插入的间距，且下划线是采用 `\makebox` 实现的，无法在一个 box 中弄两个下划线。
